### ISSUE TITLE
Currently using hapi-auth-jwt2, would like to add Facebook integration

### ISSUE THREAD

**Issue by sgentile** [dwyl/hapi-auth-jwt2#100]
Any recommendations on implementing multiple strategies with hapi-auth-jwt2 ?  We are currently using hapi-auth-jwt2, but would like to add a facebook login as well.

**Comment by nelsonic** [comment]
@sgentile good question. we have don this with Google auth but not facebook. we'd love to help you make progress with this. is any of your code for this project on GitHub?

**Comment by nelsonic** [comment]
Most people using Hapi.js opt for Bell for 3rd Party Authentication: https://github.com/dwyl/hapi-auth-jwt2/issues/100

**Comment by sgentile** [comment]
thanks - I'll try that route - (I didn't realize I could have multiple auth strategies on the hapi route as an array)
