### ISSUE TITLE
Set default scope when using hapi-auth-jwt2?

### ISSUE THREAD

**Issue by jamesdixon** [dwyl/hapi-auth-jwt2#101]
Hi,

I was attempting to set a default scope for my routes using the following code:

```javascript
server.auth.default({
        strategy: 'jwt',
        scope: ['admin']
    });
```

Unfortunately, the server throws an error saying `Cannot set the default strategy more than once.`. I attempted to pass the `scope` option into `server.auth.strategy`, but it doesn't appear to do anything.

Thanks!
James

**Comment by nelsonic** [comment]
@jamesdixon good question. any chance you can share a bit more code so we can help debug this?

**Comment by jamesdixon** [comment]
@nelsonic I actually, just solved the issue. For anyone looking to set a default scope, make sure yous et the `mode` for your strategy to `false` and then use `server.auth.default({options...})` to register your defaults.

```javascript
  // setup authentication strategy
  server.auth.strategy('jwt', 'jwt', false, {
    key: process.env.JWT_SECRET,
    validateFunc: require('./utils/auth/validateToken'),
    verifyOptions: {
      algorithms: ['HS256']
    }
  });

  // set default scope for authenticated routes
  server.auth.default({
    scope: ['admin']
  });
``` 
Thanks!
James

**Comment by iteles** [comment]
@jamesdixon This is a great simple solution and I'm sure there'll be other people asking the same question. Do you have time to put in a PR to the readme? :blush:
