### ISSUE TITLE
Allow additional strategies to authenticate if no token is found

### ISSUE THREAD

**Issue by martinj** [dwyl/hapi-auth-jwt2#104]
If no token is found please return an empty error with scheme name to allow aditional strategies to be tried. e.g 

`return reply(Boom.unauthorized(null, 'Token'))`

From hapi documentation http://hapijs.com/api#serverauthschemename-scheme:

```If the err returned by the reply() method includes a message, no additional strategies will be attempted. If the err does not include a message but does include a scheme name (e.g. Boom.unauthorized(null, 'Custom')), additional strategies will be attempted in order of preference.```

Due to changes in #6 the side effect are that you can't use this with additional strategies that allows for other auth scheme in authorization header, so i would like to se that reverted. Scheme name should be present in the authorization header according to rfc http://www.ietf.org/rfc/rfc2617.txt

**Comment by nelsonic** [comment]
@martinj we absolutely *do* want to allow/encourage additional strategies, 
which additional strategy are you *hoping* to use on your project?

**Comment by martinj** [comment]
In my case i was using hapi-auth-bearer-token with a different tokenType.

**Comment by nelsonic** [comment]
Out of *curiosity* what is the other type of Token?

**Comment by martinj** [comment]
Its an option to hapi-auth-bearer to set a specific scheme in authorization header.
From their docs:
```tokenType (Default: 'Bearer') - Allow custom token type, e.g. Authorization: Basic 12345678```

**Comment by nelsonic** [comment]
@martinj are you referring to *this* project: https://www.npmjs.com/package/hapi-auth-bearer ?

**Comment by martinj** [comment]
No, this project https://github.com/johnbrett/hapi-auth-bearer-token

**Comment by nelsonic** [comment]
Oh. Right.  :+1:
