### ISSUE TITLE
Why do we need JWT.verify?

### ISSUE THREAD

**Issue by bboysathish** [dwyl/hapi-auth-jwt2#106]
Can you answer this question?

i was following your tutorial,
https://github.com/dwyl/hapi-auth-jwt2-example

Suddenly, i was thinking why i need to JWT.verify?
http://stackoverflow.com/questions/32811978/do-i-need-to-verify-jwt

P.S : i am a node-newbie. i am trying to learn things. If it was already explained anywhere, please point me out there. 

Thanks,

**Comment by nelsonic** [comment]
Hi @bboysathish thanks for your question!
Have you had a chance to read our introduction to JSON Web Tokens: https://github.com/dwyl/learn-json-web-tokens ?
The purpose of `JWT.verify` is to check that the Token the client is sending to the server was in fact originally signed using the `secret key` otherwise we have no way of knowing the request is from an *authorised* person...

**Comment by bboysathish** [comment]
Thanks for the reply, I will look into that link, Another question 
```
The purpose of JWT.verify is to check that the Token the client is sending to the server was in fact originally signed using the secret key otherwise we have no way of knowing the request is from an authorized person...
```
1. So an identical JWT can be generated with some other secret key and can be passed to my server?
2. Even though above can be done, jwt shouldn't be different? How can one generate an identical jwt without knowing my secret key?

Consider this scenario, 

If i generate jwt sign token - "eeee.1222.4444" with secret key "secret" and i am storing it in redis as key value pair,

```
"eeee.1222.4444" - {"extra":"values"}
```
and return that token to client.

Now the client will send that token in authorization header, i can use redis.exist("eeee.1222.4444") to check that the token is generated by me and its exist in my database.

Now where in this scenario i need to use JWT.verify?

Thanks once again.

**Comment by nelsonic** [comment]
The probability of an "*identical*" JWT using HS256 algorithm (2^256 ) is 1 in 1.1579209e+77 
in other words less probable than the *universe spontaneously imploding* ...

See: http://crypto.stackexchange.com/questions/1145/how-much-would-it-cost-in-u-s-dollars-to-brute-force-a-256-bit-key-in-a-year

As for storing the *additional* data in Redis, that would be fine. :+1: 
But, if the token did not validate using `JWT.verify` which is a *Computation* (*fast*) you do not need to waste time querying Redis which is a *Network I/O* (*much slower*)

Does that make sense?

**Comment by bboysathish** [comment]
Got it ... That make sense, if i do both? (Thats my bad... ). In your example you are both verifying and querying elastic search for session information. 

```
Conclusion:
1. JWT.verify === Redis.exist/redis.get
2. Faster ----------- Slower
```

Well in my case i need to use both, because i will store that jwt in redis with 1 hour ttl, where i will extend that ttl for every hit to my server with that jwt. 

(Note: i am not using JWT exp key for checking expiration, because i dunno how can i extend jwt exp for every hit to my server.)

So, i will use JWT.verify for authentic and use redis.exist to check that token is available in redis.

i think my case is some what unique/ may be worst scenario to use jwt .

Thanks again for your patience reply.

**Comment by nelsonic** [comment]
@bboysathish replying to questions is our *mission*; you don't have to thank us. :wink: 

You can simply re-issue the JWT on each request with a new `exp` which then gets verified on subsequent requests so you can cut out Redis `ttl`. if `jwt.verify` fails (because of the *expired* token) you can require re-authentication by sending a `401` error back to the client. :+1:

**Comment by bboysathish** [comment]
If i re-issue jwt for every hit (which i think token will be different for every time we generate), the information which i stored associated with the first token must be copied and and set in redis with re-issued token right?

**Comment by nelsonic** [comment]
@bboysathish *another* ***good question***.
The answer is: *no*, there's an *easier* way.
The way we are doing it in **hapi-auth-jwt2** is to store an `id` inside the JWT and then lookup that `id` Redis. see: https://github.com/dwyl/hapi-auth-jwt2-example/blob/b8edc701de26328a001f44837eb224ab0e9e2d3a/index.js#L25
This means you can keep the `id` consistent (and thus not have to update Redis on each request) so you can change the JWT independently.

**Comment by nelsonic** [comment]
@bboysathish if your questions have *satisfactorily* answered, can you please close this issue, thanks!

**Comment by nelsonic** [comment]
Closing this issue as we have not had a response back for 11 days. @bboysathish please re-open if you need any further clarification. thanks! :+1:

**Comment by bboysathish** [comment]
@nelsonic Apologies, i was completely full with my work.. Still i have more question in this. I will open another issue with a use case to check whether i can use JWT there.Thanks a lot.. & Once again @nelsonic great response from you :)

**Comment by nelsonic** [comment]
thanks @bboysathish :+1: 
we're here to help so if you have *any* questions open as many issues as you need.
(*we just need to make sure we close them because BitHound.io grade our repo based on how long issues are open for...*)

**Comment by bboysathish** [comment]
@nelsonic , i have drafted my use case. But it is purely related to Should i use JWT or not?. Can i open a issue.

**Comment by nelsonic** [comment]
What is your use case?

**Comment by bboysathish** [comment]
Here.. https://gist.github.com/bboysathish/37855df1480f1e45d86f

**Comment by edwardcodes** [comment]
Looks good @bboysathish :+1: 
Let us know if you need any help setting it up.
Have a great weekend!

**Comment by bboysathish** [comment]
@nelsonic 
 >You can simply re-issue the JWT on each request with a new exp which then gets verified on subsequent requests so you can cut out Redis ttl. if jwt.verify fails (because of the expired token) you can require re-authentication by sending a 401 error back to the client

i got problem here... Whenever i re-issue the token, the old token is still valid right? because the exp is set to 60 min. So they can access my service with old token? Is there a way to restrict it? Like Black Listing?

**Comment by bboysathish** [comment]
@nelsonic Any ideas ?

**Comment by edwardcodes** [comment]
Good question @bboysathish!
There are *two* ways of solving this:
1. encapsulate a session token inside the JWT which gets looked up in Redis on each request. 
2. Having a Blacklist where "bad" tokens can be looked up.
You've got to ask yourself: are we going to have more good or bad tokens?

> The answer is: its more *memory efficient* to store (*only*) the "*good*" (*valid*) tokens and everything else is disallowed.

**Comment by bboysathish** [comment]
@edwardcodes Thanks for the answer.!!

Sample Scenario:

1. I have an endpoint for /login
2. I have another endpoint /addtocart
3. and Logout

*After user got loggedIn successfully, now I will issue an JWT token which has ,
```
1. UserName: ""
2. Email : ""
3. SessionInformation : { "products": "", ...}
4. SessionToken : "For this User"
5.Exp: 60Min
```
*Now the next call to the server has JWT token and it is to add items to the cart, after succesfully addition of  things to the cart, I would like to store the cart information in the JWT itself, so I will re-issue a new JWT token with once again exp set to 60Min.
```
SessionInformation : {"products": "1,2,3,4"}
Exp: 60Min
```
*Now the client has two tokens with exp of 60Min and both are authentic.

*So now the client can invoke logout service with any of the token it has. 

Problem is Token may be authentic, but i would lost the session-information and next big thing is my server is now prone to some security attacks if they keep getting new tokens for every hit and old token is valid for another 60Min.

Could you please explain how your answer fits in my scenario. So i could clearly understand and implement it.

**Comment by bboysathish** [comment]
@edwardcodes Any thoughts?

**Comment by nelsonic** [comment]
@bboysathish are you setting an actual `Date.now() + (60 * 60 * 1000)` as the `Expiry`...?

**Comment by nelsonic** [comment]
If you want to update/re-issue the JWT with more data in it, you will need to invalidate the old one in the logic of your `validateFunc`. Let us know if you need an example.

**Comment by bboysathish** [comment]
Actullay, I am setting expiry like this,
180 seconds.
```js
 expiresIn: 180 
```

**Comment by bboysathish** [comment]
Yes, @nelsonic How to invalidate that old token? Can you show me snippet?

**Comment by nelsonic** [comment]
@bboysathish it `depends` how you are storing the session details for the person.
Do you have a database? or are you attempting to store everything in the JWT?

**Comment by bboysathish** [comment]
Actually i am trying to do everything within JWT itself.
If it is not possible, i am planned to move the logic to use redis (as database) and do whatever logic you are going to say :) :100:  @nelsonic

**Comment by nelsonic** [comment]
You need to treat having *multiple* ***valid*** JWTs as multiple sessions (e.g: someone logged into your app on more than one device). Your job is to "*sync*" up the sessions so that the latest shopping cart data is propagated.

**Comment by nelsonic** [comment]
I *personally* would not include the contents of the shopping cart in the JWT without having it *persisted* to a Database *simply* on the grounds that having it in one JWT will not sync it with other devices the person may be using. This is not an issue for *many* people who use *one* device, but what we've found from building E-Commerce is that people *often* do research on their mobile device, add-to-cart to "save" it and then resume on Desktop. And, the *only* way to make this experience *seamless* is to use a database (e.g: Redis) to store that data ...

**Comment by bboysathish** [comment]
"I personally would not include the contents of the shopping cart in the JWT without having it persisted to a Database simply on the grounds that having it in one JWT will not sync it with other devices the person may be using. This is not an issue for many people who use one device, but what we've found from building E-Commerce is that people often do research on their mobile device, add-to-cart to "save" it and then resume on Desktop. And, the only way to make this experience seamless is to use a database (e.g: Redis) to store that data ..."

@nelsonic  Agreed. /Me Start using Redis :) .. Thanks for clarifying.

**Comment by nelsonic** [comment]
Redis Scales pretty well. if you get stuck let us know. :+1: 
(*preferably open a new issue so it makes it easier for others to understand what problem you are trying to solve...*)
Thanks!
Please :star:
