### ISSUE TITLE
Regression: request.auth.isAuthenticated is true and request.auth.credentials is {} when user not logged in

### ISSUE THREAD

**Issue by alanshaw** [dwyl/hapi-auth-jwt2#111]
With the latest version of the plugin my `mode: 'try'` routes exhibit this behaviour.

This did not happen previously.

**Comment by nelsonic** [comment]
Thanks very much for reporting this @alanshaw can you give us a bit more detail as to the circumstance/context where this is happening in your app so we can create a regression test and fix this.

**Comment by alanshaw** [comment]
I will submit a test when I get a sec...

**Comment by nelsonic** [comment]
Sweet. thanks! :+1:

**Comment by alanshaw** [comment]
In the mean time I rolled back to v5.1.0

**Comment by nelsonic** [comment]
Makes sense. 
We *really* did not expect the update to introduce a "*breaking"*" change...
Thanks *very* much for reporting it!

**Comment by alanshaw** [comment]
https://github.com/alanshaw/hapi-auth-jwt2/commit/736067f8f73bf7388438e399e12050489b9a400c

Both auth modes 'optional' and 'try' fail the test for `isAuthenticated` being `false`. Am I doing something wrong here?

**Comment by nelsonic** [comment]
Good question @alanshaw . :question: 
I'm busy *investigating* this now. :hourglass:
