### ISSUE TITLE
Update to Latest version of Hapi 11 ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#114]
Another week, another ***Major*** version of Hapi released ...
Does *anyone* have time to update the `devDependencies` and submit a Pull Request with the change...?

**Comment by iteles** [comment]
At least it looks like we're not using any of the CORS configuration objects that were removed or `server.after()` so this shouldn't be too onerous :+1:

**Comment by nelsonic** [comment]
Yeah, we're not doing *anything* "*fancy*"...
