### ISSUE TITLE
validateFunc not running...

### ISSUE THREAD

**Issue by Dindaleon** [dwyl/hapi-auth-jwt2#116]
Hello,

For some reason, I cannot get the validateFunc to run.

This is my code:

This is my api.js file (plugin)

    import routes from './routes';

    const validate = ( decoded, request, callback ) => {
      console.log('Validate User test');
      return callback(null, true);
    };

    const register = ( server, options, next ) => {
      server.auth.strategy(
        'jwt',
        'jwt',
        {
          key: 'my_key',
          validateFunc: validate
        }
      );
      server.auth.default('jwt');

      for (const key in routes) {
        if (routes.hasOwnProperty( key )) {
          server.route(routes[key]);
        }
      }
      next();
    };

    register.attributes = {
      name: 'api',
      version: '0.0.1'
    };

    export default register;

In the server.js file I register the api plugin and hapi-auth-jwt2 plugin

    server.register([
     {
        register: require('hapi-auth-jwt2');
      }, {
        register: api,
        routes: {
          prefix: 'path_to_api'
        }
      }
    ], ( error ) => {
      if ( error ) {
        return console.error( error );
      }
    ...

This is the route:

    {
      method: 'GET',
      path: '_path_',
      config: {
        auth: {
          strategy: 'jwt',
        }
      },
      handler: ( request, reply ) => {
        console.log('test handler')

        reply({ text: "You used a token" })
        .header("Authorization", request.headers.authorization);
      }
    }

None of the console logs get displayed. What am I missing?

When I request the routes, this is the response I get: 

    {
      "statusCode": 401,
      "error": "Unauthorized",
      "message": "Missing authentication"
    }

**EDIT** I am using Joi for validation and hapi-swagger for as API interface.

**Comment by eventhough** [comment]
@Dindaleon It looks like route authentication is working as expected. Hapi is telling you that your request is missing an `Authorization` header. Can you show us what your request looks like? Make sure you set the header like so:

```
GET /widgets HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: [JWT TOKEN GOES HERE]
Cache-Control: no-cache
```

I believe hapi-auth-jwt2 supports header fields, cookies, and URL tokens now.

**Comment by Dindaleon** [comment]
yes, it seems is missing, this is the request header:

    GET /api/v1/users/list HTTP/1.1
    Host: localhost:3000
    Connection: keep-alive
    Cache-Control: max-age=0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    X-FirePHP-Version: 0.0.6
    Upgrade-Insecure-Requests: 1
    Accept-Encoding: gzip, deflate, sdch
    Accept-Language: es-ES,es;q=0.8,en;q=0.6

Sorry for the dumb question, but where do I set the Authorization header?

**Comment by eventhough** [comment]
It depends. What library are you using to handle http requests?

Here are some popular node libraries:

- https://github.com/visionmedia/superagent
- https://github.com/mzabriskie/axios
- https://www.npmjs.com/package/whatwg-fetch

All are great choices. If you're using a different platform there are
probably other http clients available.

**Comment by Dindaleon** [comment]
Good! Thank you, I forgot to mention that I am using joi for validation and hapi-swagger for the API interface, sorry! So, to set an authorization header, I just had to add a header field to the route:

    validate: {
        params: {
            a: Joi.number()
                .required()
                .description('the first number'),

            b: Joi.number()
                .required()
                .description('the second number')
        },
        headers: Joi.object({
             'authorization': Joi.string().required()
        }).unknown()
    }

**Comment by Dindaleon** [comment]
Sorry but I had to reopen my issue, it now sends the authorization header:

    GET /api/v1/users/list HTTP/1.1
    Host: localhost:3000
    Connection: keep-alive
    Accept: application/json
    User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
    X-FirePHP-Version: 0.0.6
    Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0b3B0YWwuY29tIiwiZXhwIjoxNDI2NDIwODAwLCJodHRwOi8vdG9wdGFsLmNvbS9qd3RfY2xhaW1zL2lzX2FkbWluIjp0cnVlLCJjb21wYW55IjoiVG9wdGFsIiwiYXdlc29tZSI6dHJ1ZX0.yRQYnWzskCZUxPwaQupWkiUzKELZ49eM7oWxAQK_ZXw
    Referer: http://localhost:3000/api/v1/documentation
    Accept-Encoding: gzip, deflate, sdch
    Accept-Language: es-ES,es;q=0.8,en;q=0.6

However, I now get another response error:

response body:

    {
      "statusCode": 401,
      "error": "Unauthorized",
      "message": "Invalid token",
      "attributes": {
        "error": "Invalid token"
      }
    }

response header:

    {
      "Date": "Sun, 25 Oct 2015 22:47:29 GMT",
      "Content-Encoding": "gzip",
      "Www-Authenticate": "Token error=\"Invalid token\"",
      "Transfer-Encoding": "chunked",
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-cache",
      "Connection": "keep-alive",
      "Vary": "accept-encoding"
    }

And I see that the `validate` functions is still not running.

**Comment by eventhough** [comment]
This could be a problem with how you are signing your tokens. Input your token here with secret and see if your token is valid: http://jwt.io/

**Comment by Dindaleon** [comment]
Yes indeed. The secret key was wrong. Dumb mistake. Thank you for your help.
