### ISSUE TITLE
Support for multiple strategies

### ISSUE THREAD

**Issue by richardlay** [dwyl/hapi-auth-jwt2#117]
I have an issue where I'm also using a basic auth strategy along side the jwt strategy.

When I set the mode to "try" and use a basic auth string in the Authorization header, the jwt strategy will try to verify and fails. It replies with a Boom error and includes an error message, which then prevents the basic auth strategy from being tried.

To comply with hapi's try and optional modes, you'd have to remove the error message I think.

**Comment by bboysathish** [comment]
By going through the documentation,http://hapijs.com/api#route-options

If i understood correctly,the below point says, 'try' mode will try then authentication if it fails it will continue executing the request.

```js
'try' - same as 'optional' but allows for invalid authentication.
```
@richardlay How are you planning to have two strategies in try mode?

**Comment by richardlay** [comment]
I have something like this:
server.auth.default({
   mode: "try",
   strategies: ["token", "bearer"]
});

Where the token strategy is using hapi-auth-jwt2, and the bearer strategy is a different library. What I expect to happen is that if the token strategy fails, it will try the next strategy. However, currently it does not do this.

**Comment by nelsonic** [comment]
@richardlay if you have time to submit a Pull Request, please re-open this issue and submit the PR. (*Closing for now due to inactivity.*)
