### ISSUE TITLE
How to debug the validateFunc?

### ISSUE THREAD

**Issue by chapati23** [dwyl/hapi-auth-jwt2#125]
guys, sorry if this is a stupid question but i've wasted half a day on this already:

no matter what i try (console.log/console.error/server.log etc.)

my validateFunc always fails silently, no output whatsoever. and i have no idea what exactly is going wrong.

how can i get it to at least output some debug info?

**Comment by nelsonic** [comment]
Hi @chapati23, not a stupid question at all. Is your code online somewhere so we can help debug?

**Comment by chapati23** [comment]
hey @nelsonic, thanks for the quick reply. so this is my app, mostly derived from your example:
your example works as expected but i'm trying to bring auth0 into the equation and for that matter i need to be able du debug the validate function. have also tried with good/good-console but same result, now output.

do i have to re-route the console.log to some other place?

``` es6
import config from './config';
import Hapi from 'hapi';
import Auth0 from 'auth0';

const auth0 = new Auth0({
  domain:       config.auth0Domain,
  clientID:     config.auth0ClientID,
  clientSecret: config.auth0ClientSecret
});

var people = {
    1: { // eslint-disable-line quote-props
      id: 1,
      name: 'Jen Jones'
    }
};

// bring your own validation function
var validate = (decoded, request, callback) => { // eslint-disable-line no-unused-vars
  console.log('why am i not showing');

    // do your checks to see if the person is valid
    if (!people[decoded.id]) {
      return callback(null, false);
    }

    return callback(null, true);
};

var server = new Hapi.Server();
server.connection({ port: 8000 });

// include our module here ↓↓
server.register(require('hapi-auth-jwt2'), (err) => {
    if (err) {
      console.log(err);
    }

    server.auth.strategy('jwt', 'jwt',
    { key: 'NeverShareYourSecret',             // Never Share your secret key
      validateFunc: validate,                  // validate function defined above
      verifyOptions: { algorithms: ['HS256'] } // pick a strong algorithm
    });

    server.auth.default('jwt');

    server.route([
      {
        method: "GET", path: "/", config: { auth: false },
        handler: (request, reply) => { // eslint-disable-line no-unused-vars
          reply({ text: 'Token not required' });
        }
      },
      {
        method: 'GET', path: '/restricted', config: { auth: 'jwt' },
        handler: function(request, reply) {
          reply({ text: 'You used a Token!' })
          .header("Authorization", request.headers.authorization);
        }
      }
    ]);
});

server.start(() => {
  console.log('Server running at:', server.info.uri);
});
```

**Comment by nelsonic** [comment]
@chapati23 how are you attempting to access the `/restricted` route? did you try to `cURL`?
also, what 3rd party provider are you using with Auth0?

**Comment by chapati23** [comment]
I was using postman. but i didn't chose an auth-method. after i chose basic auth I at least got some errors. So the validate function only seems to run when the correct headers are set, is that correct?

**Comment by nelsonic** [comment]
Correct, one of the key objectives of an authentication scheme (e.g. `hapi-auth-jwt2` plugin/module) is to *reject* any requests to a given route as early as possible to avoid consuming resources on the server.
So any request that does not have a valid JWT will be rejected an *never reach* the `validate` function.

**Comment by nelsonic** [comment]
Using postman, you should attempt to access `/restricted?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkFudGhvbnkgVmFsaWQgVXNlciIsImlhdCI6MTQyNTQ3MzUzNX0.KA68l60mjiC8EXaC2odnjFwdIDxE__iDu5RwLdN1F2A`
i.e. a valid JWT ...

or if you `cURL` use the example in the readme:

```sh
curl -v -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkFudGhvbnkgVmFsaWQgVXNlciIsImlhdCI6MTQyNTQ3MzUzNX0.KA68l60mjiC8EXaC2odnjFwdIDxE__iDu5RwLdN1F2A" \
http://localhost:8000/restricted
```

**Comment by chapati23** [comment]
Thank you, consider this solved :)

**Comment by iteles** [comment]
Thanks for coming back to close the issue @chapati23! Do please add any more info you used to solve the issue in case anyone else is facing the same problem :blush:

**Comment by chapati23** [comment]
Well, as my issue was more of an issue with understanding I can't really add anything other than saying that I know understand that the validate() handler is never executed without a valid JWT in the request.
