### ISSUE TITLE
Accept Promises in validateFunc

### ISSUE THREAD

**Issue by gausie** [dwyl/hapi-auth-jwt2#127]
I should be able to return a Promise instead of using a callback in validateFunc.

**Comment by nelsonic** [comment]
@gausie what would be the *advantage* of using `Promises` in this situation...?

**Comment by nelsonic** [comment]
@gausie, have you tried to "*Promisify*" it? http://bluebirdjs.com/docs/api/promise.promisify.html

**Comment by gausie** [comment]
Would just be nice to be able to support both without needing Bluebird.

**Comment by nelsonic** [comment]
@gausie if you have time to PR support for promises, please re-open and submit the PR.
for now, I am closing this issue as Promises in Auth is not something I've seen anywhere in Hapi-land or seen requested by anyone else.
