### ISSUE TITLE
question: how does ignoreExpiration: false works?

### ISSUE THREAD

**Issue by fouadkada** [dwyl/hapi-auth-jwt2#129]
Hey,

I have a login endpoint that sends a token using the jsonwebtoken module
```
response.setSuccess(true).setData({user: user,token: jwt.sign(user, config.JWT.key, {expiresIn: 60 * 5})});
```

my question is the following: what is the use of ignoreExpiration: false in hapi-auth-jwt2, does it check if the token has expired automatically or is it something that needs to be done manually in the validate function?

an example would be highly appreciated.

Thanks

**Comment by eventhough** [comment]
@fouadkada Yes, hapi-auth-jwt2 checks for token expiration automatically. If a token is expired, it will return a 401 unauthorized. If you do not want hapi-auth-jwt2 to check token expiration, you can set `ignoreExpiration` to true but this is not recommended.

**Comment by fouadkada** [comment]
thanks @eventhough for the reply, what the unit of time(sesonds, milliseconds...)? is it possible to provide a small working example?

**Comment by eventhough** [comment]
@fouadkada Expiration is in seconds, but there are many more options as well. This link should help you: https://github.com/auth0/node-jsonwebtoken

It contains all the settings used by hapi-auth-jwt2. They are basically the same settings since we pass options through directly.

**Comment by nelsonic** [comment]
as @eventhough states, Expiration time is in seconds. 
There is a usage example in the test: https://github.com/dwyl/hapi-auth-jwt2/blob/6ae2d35f32c49de5a46d7f3926b250e0e1ce9b3e/test/basic_test.js#L106-L115
Please let us know if that answers your question or if not, please re-open the issue. thanks!
