### ISSUE TITLE
Diagram to explain how this module works (for complete beginners)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#131]
should we have a diagram to explain how this works?

**Comment by nelsonic** [comment]
![hapi-auth-jwt2-diagram-verify](https://cloud.githubusercontent.com/assets/194400/11935134/0bb7d156-a7fe-11e5-893b-a43a6e7ced2d.png)

**Comment by nelsonic** [comment]
With box around the bouncer:
![hapi-auth-jwt2-diagram-verify 1](https://cloud.githubusercontent.com/assets/194400/11937066/e104b6ca-a809-11e5-8b3b-618fb5ca9adb.jpg)

**Comment by iteles** [comment]
:laughing: at the bouncer

**Comment by nelsonic** [comment]
Maybe We should add a VA task to come up with a betterer diagram...

**Comment by eventhough** [comment]
@nelsonic You are too fast. I love the graphic of the bouncer. My only feedback: the diagram is a *bit* light on details. If people are looking for this package, they probably already made the decision to use JWT auth **OR** they are deciding on an auth strategy. Maybe we can show that hapi-auth-jwt plays well with header, url, and cookie tokens...or that it works with other strategies? We could also show how cool it is to use JWT vs session based authentication.

I took a crack at drafting something up to show what I mean...very rough.

<img width="1175" alt="screenshot 2015-12-21 10 11 03" src="https://cloud.githubusercontent.com/assets/443149/11938155/a5fa9554-a7cd-11e5-92b1-01efd6841ded.png">

**Comment by nelsonic** [comment]
@eventhough having an explanatory diagram would make way more sense. Please flesh it out when you have time and PR. :+1:

**Comment by nelsonic** [comment]
@eventhough I added your diagram to the readme. hope that's ok. :+1:
