### ISSUE TITLE
question: Can we make the throw on extract.isValid optional when supplying verifyFunc?

### ISSUE THREAD

**Issue by vprasanth** [dwyl/hapi-auth-jwt2#139]
I'm going to prefix this question with the fact that perhaps this type of strategy isn't exactly jwt.. so perhaps I shouldn't be trying to do this within `verifyFunc` at all.. so forgive my ignorance in advance :) 

I want all my api endpoints to require authorization with jwts. However, instead of creating an endpoint that returns a jwt to use for all future requests, I wanted the authentication functionality built in to the `verifyFunc`.

So effectively, a request could be made with some other type of token which I can authenticate and provide back a jwt token.

Currently even when `verifyfunc` is provided the token is checked and throws if the token doesn't look like a jwt. 

Thanks!

**Comment by nelsonic** [comment]
@vprasanth, thanks for your question & welcome to *DWYL*! :smiley: 
In the *latest* version of this package we added the option to specify your own `verifyFunc` 
in other words you have ***full control*** over the `JWT.verify` function. 
see: https://github.com/dwyl/hapi-auth-jwt2#advancedalternative-usage--bring-your-own-verifyfunc
For an *example* of a `customVerifyFunc` see: https://github.com/dwyl/hapi-auth-jwt2/blob/0385361ca7da34daed4256b0e2d2d01c22a73a1b/test/verify_func_server.js#L21

Please let us know if you have any other questions on implementation. :+1:

**Comment by vprasanth** [comment]
@nelsonic Thanks! This repo has bee hugely resourceful!! I had a look at the sample code. However the problem is I never get in to my `verifyFunc`, the error is thrown within the strategy implementation. 

```javascript
 if (!extract.isValid(token)) { // quick check for validity of token format
        return reply(Boom.unauthorized('Invalid token format', 'Token'));
      } /
```
https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L36

Like I said, perhaps this isn't something I should be doing :S

**Comment by nelsonic** [comment]
@vprasanth ah... 
so the `!extract.isValid()` call is just checking the *format* of the token: https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/extract.js#L35 
if its not in 3 sections its not a JWT...
So, do you want to be able to *specify* the way the error gets handled if we *know* the token is not a JWT...?
See, our philosophy is that we want to *reject* a request as quick as *possible* if it does not contain a JWT to not tie up the Node Process...
So you want to be able to *recognise* a *different* `type` of Token and then respond with a JWT...?

**Comment by vprasanth** [comment]
@nelsonic Yep, I want to recognize a different type of token, auth it, and return a jwt. I didn't even think about Node Process :( Perhaps I shouldn't be doing it this way... :(

**Comment by vprasanth** [comment]
@nelsonic I think I for a better solution. I could set the authentication mode to `try` then use the auth credentials to do the authentication/signing and returning of jwt for first timers :) I tried to see if I could do that earlier, but looks like I added the mode to the wrong route... my apologies

**Comment by nelsonic** [comment]
*exactly*! thanks for answering your own question... :wink: 
Once you have it working an have no further queries for us, please close this issue. thanks! :+1:

**Comment by nelsonic** [comment]
@vprasanth are you still having any issues using the module? 
If you're up-and-running please *close* this issue. thanks. :+1:
