### ISSUE TITLE
Question: What to check with validateFunc

### ISSUE THREAD

**Issue by Nargonath** [dwyl/hapi-auth-jwt2#141]
I'm learning JWT and I chose your lib for my Hapi project. Thanks for writing it by the way. ;)

One thing that I don't understand is as JWT is used to rely on the data contained in the token, I don't see the need to check whether the user exists or not in the db. As your lib already verifies the token and decodes it. What other validation would be needed in the validateFunc? What do you guys usually check in the validateFunc? I'm asking the question as this function is required by the lib hence some important checks must be done with it I guess.

I apologized if that's a trivial question, but I'm a bit confused on that matter.

**Comment by vdeturckheim** [comment]
Hi,
There is actually different use cases for the validateFunc, I'll try to list 2 of them;
* jti field check: you can set a token id and ensure it is still valid
* credentials decoration: Hapi let you use scopes to set user access rights on each routes. If some data are not meant to be published in a jwt (because they are confidential or subject to reguler changes) you may want to query them here and add them to your credential objects

I hop that helps !

**Comment by Nargonath** [comment]
@vdeturckheim ok thank you for the examples. I see the point of it.

**Comment by adam-beck** [comment]
@vdeturckheim These still seem like cases that you may not find necessary every time this plugin is used. Has there ever been discussion regarding a "default" `validateFunc` that would check any token it receives against the secret? This is similar behavior to how `hapi-auth-jwt` handles it and I think that is a nice feature to have built in.

**Comment by vdeturckheim** [comment]
@adam-beck Sorry for the late response, I just came back from vacations. 
If I understand, you would like to have the following behavior added:
-> If no `validateFunc` is present, a default one is called. This default function would set the jwt as credential objects
Am I right ?
@nelsonic AFAIK, that would also close the issues regarding the use of the plugin directly with Glue (even if I do not really recommend it, it might be the response to a common need). Would you accept a PR doing this ? If so, I'll try to find time this week to do so.

**Comment by adam-beck** [comment]
@vdeturckheim yes something along those lines. I find myself doing this very often:

```
function validate(decoded, request, callback) {
  // if the user has a valid JWT then he/she has already been successfully authenticated
  // so there isn't much reason for any further validation
  // this validate function just checks that the user has a valid JWT and passes it on
  return callback(null, !!decoded);
}
```
