### ISSUE TITLE
node engine version

### ISSUE THREAD

**Issue by salzhrani** [dwyl/hapi-auth-jwt2#142]
`engine` in `package.json` was updated to `4.2.6` when hapi was update to 13. unless a specific patch is required, I recommend keeping it at `>=4.2.0` since it is what hapi has and covers the most LTS versions.

**Comment by nelsonic** [comment]
@salzhrani thanks for getting in touch.
I *agree* that we should not *force* people to *have* to update their version of Node.js to `4.2.6`, 
Apologies if this is giving you a warning when you `npm install` or `npm update` ...

The current `package.json` on *master* of Hapi says it supports `v4.0.0` (LTS)  which is very "*loose*" ...
https://github.com/hapijs/hapi/blob/05bfc3e774966332d369465d436c1fa433664b8d/package.json#L18

There was ***security update*** in `4.2.3` which should not be ignored 
https://github.com/nodejs/node/blob/v4.2.6/CHANGELOG.md#2015-12-04-version-423-argon-lts-rvagg
and we really should *encourage* people to use the latest version of Node LTS for their own benefit ...

How about we meet in the middle and say `>=4.2.3` so we at least we are encouraging people to update their production server to the latest *security* release...?

**Comment by salzhrani** [comment]
:+1:

**Comment by nelsonic** [comment]
@salzhrani fixed. new version on NPM: `5.4.1` recommends Node `4.2.3` LTS :+1: 
Thanks again for using the plugin! please :star: to help us get the word out. :wink:

**Comment by gilly3** [comment]
Changing the minimum required node version should be considered a breaking change.  So, before you publish a package with a change to the node version, you should first bump your package's major version number.

Will 5.4.1 still run on node 4.1.1?

**Comment by nelsonic** [comment]
@gilly3 good question. 
The node version is *really* only a *recommendation*. 
This plugin has *zero* ES6 code and none of the `dependencies` have ES6 code (*at the time of writing*).
Therefore it still works on node v.0.10 for the people using Hapi 8...
I agree 100% that if we had *broken* backward compatibility with previous versions of node we would have bumped the plugin (package) version up a major number.
