### ISSUE TITLE
How to check on a auth: false route if the user have a valid token?

### ISSUE THREAD

**Issue by MacTheZazou** [dwyl/hapi-auth-jwt2#147]
I want to implement a refresh token system [explanation here](https://auth0.com/blog/2015/10/07/refresh-tokens-what-are-they-and-when-to-use-them/)

but the problem is that I need to check on the auth route if the user have this valid refresh token... but the route needs to be auth: false...

any idea?

Thank you

**Comment by MacTheZazou** [comment]
Sorry, I just found the solution in the doc...

Sorry again!

**Comment by nelsonic** [comment]
@MacTheZazou glad you found your solution. :+1:
