### ISSUE TITLE
redirectURL on validation error

### ISSUE THREAD

**Issue by goncalvesr2** [dwyl/hapi-auth-jwt2#148]
Hi,

thanks for the great work.
Regarding issue https://github.com/dwyl/hapi-auth-jwt2/issues/78 I would like to vote for the "redirect key to the Options parameters". With it we would be able to include it whenever nedded (in routes to pages for example).

**Comment by nelsonic** [comment]
Hi Rui, if you can make a suggestion for how it should be implemented we'd love your input. 👍

**Comment by nelsonic** [comment]
Same as #161 
Suggestions/PR still welcome!
