### ISSUE TITLE
Invalid token in example?

### ISSUE THREAD

**Issue by naazy** [dwyl/hapi-auth-jwt2#150]
I'm not sure if the example jwt token in the curl command is valid anymore. The console returned a message saying I had successfully entered a token but I was still unable to access the /restricted page.

**Comment by nelsonic** [comment]
Ah, good question. Lets investigate ...

**Comment by anttilinno** [comment]
No, seems to work. Did npm update and upgraded node to v5.8.0.

My package.json, in case it is somehow relevant
<pre>
{
  "name": "tryhapistructure",
  "version": "1.0.0",
  "description": "Try and write in meaningful structure",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "confidence": "^1.4.2",
    "glue": "^3.1.0",
    "hapi": "^13.0.0",
    "hapi-auth-jwt2": "^5.4.1",
    "hapi-knex-objection-builder": "git+https://github.com/anttilinno/hapi-knex-objection-builder.git",
    "hoek": "^3.0.4",
    "knex": "^0.9.0",
    "moment": "^2.11.2",
    "objection": "^0.4.0",
    "pg": "^4.4.4",
    "pg-hstore": "^2.3.2"
  }
}
</pre>

**Comment by nelsonic** [comment]
@naazy were you able to get this working?

**Comment by clooth** [comment]
How I see this problem is that they're trying to access the page *in the browser* after running the curl command, which then fails since the token is not passed along.

**Comment by nelsonic** [comment]
@clooth agreed. 👍 
@naazy I've updated the docs in the readme:
https://github.com/dwyl/hapi-auth-jwt2#token-required
there's an example for browser usage. 
closing. 
please re-open if you are still having issues.
thanks.
