### ISSUE TITLE
Swagger support?

### ISSUE THREAD

**Issue by Kitanotori** [dwyl/hapi-auth-jwt2#154]
Any idea how to get hapi-auth-jwt2 set up via Swagger definition? I've been trying [the official Node.js Swagger library](https://github.com/swagger-api/swagger-node) and [a similar library](https://github.com/krakenjs/swaggerize-hapi) provided by PayPal's kraken.js team, but I have no idea how to set up authentication and authorization.

**Comment by nelsonic** [comment]
@Kitanotori good question. Can you please give us an example of your usage?
This is more of a question for @glennjones ... see: https://github.com/glennjones/hapi-swagger

**Comment by Kitanotori** [comment]
@nelsonic In order to use Swagger libraries that generate routes on-the-fly (e.g. swaggerize-hapi, swagger-node) from Swagger definition file, I need to be able to define authentication and authorization per-route. However, I can't find information anywhere on how to do this. hapi-swagger is not the right place to ask, because hapi-swagger does the opposite, i.e. generates Swagger definition from the routes that you have first written yourself. I tried swaggerize-hapi and swagger-node, and I want to use either one of them because being able to define all my Hapi routes in Swagger definition file would be a huge benefit.

For a clarification, the idea is to define routes in [Swagger definition file ](http://swagger.io/specification/), specifying a handler for each route (see examples e.g. [here](https://github.com/swagger-api/swagger-node/blob/master/docs/controllers.md)). Swagger is a language- and framework-independent standard, and being able to use it with Hapi and the relevant authentication/authorization solutions would make applications and APIs more maintainable and decoupled.

**Comment by clivend** [comment]
+1

**Comment by glennjones** [comment]
As mentioned above you can generate a API from designing Swagger first.  If you wish to take the other HAPI approach designing your endpoints using JOI first, a while ago I built a full example of using this plug-in and hapi-swagger https://github.com/glennjones/hapi-token-docs 

Not a answer to this issue, but the link may be useful to other people reading this thread

**Comment by nelsonic** [comment]
@Kitanotori I don't think using `hapi-auth-jwt2` _precludes_ you from _generating_ your routes using a swagger "builder" ... please re-open if I have miss-understood.

**Comment by Kitanotori** [comment]
I think you misunderstood. I don't want to generate routes into a file, but I want to generate them on-the-fly using [swaggerize-hapi](https://github.com/krakenjs/swaggerize-hapi), or similar Swagger-compliant library that generates the routes on-the-fly from the Swagger definition file. The problem is, hapi-auth-jwt2 does not seem to support any standard or custom Swagger configuration parameters, so I don't know how I should proceed. 

I want to be able to set any particular route defined in Swagger definition file to use hapi-auth-jwt2 for authentication **without having to generate and edit route file(s) by hand, because that would destroy the whole purpose of using Swagger-compliant route autogeneration.**

**Comment by nelsonic** [comment]
Ah... Ok. So is there a _checklist_ or guide on [`swaggerize-hapi`](https://github.com/krakenjs/swaggerize-hapi) that would ensure that [`hapi-auth-jwt2`](https://github.com/dwyl/hapi-auth-jwt2) is compatible? (_please excuse my ignorance, haven't used Swagger in a while..._)

**Comment by Kitanotori** [comment]
I created issue also there (https://github.com/krakenjs/swaggerize-hapi/issues/46), and also posted question to [StackOverflow](http://stackoverflow.com/questions/35990191/how-should-i-use-swagger-with-hapi) but so far no progress. I don't know the architecture of these two two libraries well enough, so I'm not sure what is the best way to proceed.

Btw,. I recommend trying out Swagger and particularly swaggerize-hapi, because they provide an awesome way for platform-independent and standard API definition, plus you get Hapi routes automatically generated from the definition. This should be the direction for the whole Hapi community, imho.

Currently the way to set up JWT authentication for a Hapi route is by this syntax, right?
```
	 config: {
		 auth: {
			 strategy: 'jwt',
			 scope: ['admin', 'user', '...']
		 }
	 }
```
The problem is, I want to specify the strategy and the scope in the Swagger definition file so that swaggerize-hapi generates the appropriate route applying these settings.

[Here](http://stackoverflow.com/questions/32910065/how-can-i-represent-authorization-bearer-token-in-a-swagger-spec-swagger-j) and [here](https://github.com/OAI/OpenAPI-Specification/issues/583) seems to be some talk about the same problem, although unrelated to Hapi. I guess this is mainly problem of Swagger 2.0 specification.

It might be actually that no change is necessary to hapi-auth-jwt2, but I wanted to post also here so that people struggling with the same problem could find information easily.
