### ISSUE TITLE
issue with jwt auth, and basic auth on safari

### ISSUE THREAD

**Issue by benjaminlees** [dwyl/hapi-auth-jwt2#155]
On safari the basic auth is cached and so the browser replaces the 'authorization' jwt token with basic auth token.

As the module only checks that a authorization header exists and not that it is a verified jwt token, it breaks with the error `invalid token format`. 

```
  else if (request.headers.authorization) {
    if (typeof options.tokenType === 'string') {
      var token = request.headers.authorization.match(new RegExp(options.tokenType + '\\s+([^$]+)', 'i'));
      auth = token === null ? null : token[1];
    } else {
      auth = request.headers.authorization;
    }
  }
``` 
I believe this issue could be solved with some basic defensive coding and i have no problem making a pr.

**Comment by nelsonic** [comment]
@benjaminlees as discussed, happy to remote-pair on a PR to get this working in Safari. :+1:

**Comment by benjaminlees** [comment]
@nelsonic hi not sure if i can make a pr

**Comment by nelsonic** [comment]
@benjaminlees you should have access ...

**Comment by nelsonic** [comment]
@benjaminlees please confirm that the release from your PR #157 has fixed this issue and close. thanks.

**Comment by benjaminlees** [comment]
@nelsonic  yep its closed
