### ISSUE TITLE
how to customize response when auth fails?

### ISSUE THREAD

**Issue by liesislukas** [dwyl/hapi-auth-jwt2#162]
i want to change this response

```
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Invalid token",
  "attributes": {
    "error": "Invalid token"
  }
}
```

to e.g.

```
{
error: "Invalid token"
}
```
and send different http code (not 401)

what's best way to do it?

**Comment by neurotech** [comment]
I'd like to know something similar. I use [Rollbar](https://rollbar.com/) to capture errors/exceptions/events. I want my application to be able to send `auth failed`/`unauthorised` events to Rollbar as they occur - is there any way to do this?

**Comment by nelsonic** [comment]
@liesislukas / @neurotech are you building an API or a web application? 
(*specifically are you rendering HTML views or sending JSON to the consumers of your app?*)

**Comment by neurotech** [comment]
@nelsonic I am building an API.

**Comment by jmm** [comment]
@liesislukas One option you should be able to use is registering an `onPreResponse` handler. Example:

```js
server.ext("onPreResponse", function (request, reply) {
  /*
  If authentication failed, request.response will be a Boom error object. Modify
  response.output.statusCode and / or response.output.payload properties.
  */

  reply.continue();
});
```

It's possible you could also do it with an event handler, but I'm not sure.

@neurotech You could probably also use `onPreResponse` by inspecting the response object, or you might be able to do it more directly / earlier via a [request event](http://hapijs.com/api#request-logs) handler, looking for a tag like `unauthenticated` for example.

**Comment by nelsonic** [comment]
@liesislukas see: https://github.com/dwyl/hapi-error#under-the-hood--implementation-detail for example of `onPreResponse` code.

**Comment by liesislukas** [comment]
thanks for answers, i already built that project 3 months ago so can't comment, maybe it will help for other devs.

**Comment by nelsonic** [comment]
Closing. For others, who need to customise errors in hapi apps see:  https://github.com/dwyl/hapi-error
