### ISSUE TITLE
ValidationError: "expiresInSeconds" is not allowed

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#166]
Auth0 have removed the "expiresInSeconds" option from `jsonwebtoken` v.6 ...
![expiresinseconds-no-longer-an-option](https://cloud.githubusercontent.com/assets/194400/14939059/e23ce264-0f2f-11e6-9ddc-df49d427cf76.png)

**Comment by iteles** [comment]
Failing test was removed in latest PR due to lack of support.
