### ISSUE TITLE
Mistake in readme or in 'optional' mode?

### ISSUE THREAD

**Issue by bartlomiej-korpus** [dwyl/hapi-auth-jwt2#168]
Hello,
I found it inconsistent that readme states that 

>  if no Authorization header is provided, request will pass with request.auth.isAuthenticated set to true and request.auth.credentials set to empty object

for optional authentication mode. The behaviour is actually opposite, the request will continue with isAuthenticated set to false and credentials set to null.

Is this a problem with library?

**Comment by nelsonic** [comment]
Great question @bartlomiej-korpus 👍 
We have a test that illustrates the *correct* behaviour: https://github.com/dwyl/hapi-auth-jwt2/blob/master/test/try_and_optional_auth_mode.test.js#L50
You are *correct* the Readme has to be updated to reflect this.
https://github.com/dwyl/hapi-auth-jwt2/blame/master/README.md#L259
http://hapijs.com/tutorials/auth#mode

Do you have time to send us a Pull Request fixing the Readme?  (*Dzięki*!)

**Comment by nelsonic** [comment]
This has been fixed by PR: #170 👍
