### ISSUE TITLE
Get access to verified data via route handler

### ISSUE THREAD

**Issue by sean-hill** [dwyl/hapi-auth-jwt2#169]
Say I lookup a user in my DB with the `decoded` variable in my `validateFun`, is there a way I can pass on that user data into my route's handler so that I don't have to look it up the user again with the `JWT` in the route handler? Thanks.

**Comment by nelsonic** [comment]
@sean-hill good question. So if I understand correctly, you want to have access to the `data` you looked up in your DB during the `validateFunc` ? 
There are ***two ways you can do this***:

1. the `validateFunc` takes a `callback` which accepts **3 arguments**: `(err, valid, credentials)`
see: [/lib/index.js#L65](https://github.com/dwyl/hapi-auth-jwt2/blob/fe1dae1d55b64b017f93790a29e99d4815dbb307/lib/index.js#L65)
If you pass your DB `res` as the 3rd argument it will be available in the `request.auth.credentials` Object.

2. the *easy* way of retaining access to it for later would be to add it to the `request` Object using a "*private property*" e.g: `request._userdata = db.res` which would mean that `request._userdata` is available for the rest of your request lifecycle. 

The first option is the more "*official*" Hapi way of doing it. 👍

**Comment by sean-hill** [comment]
@nelsonic you're a genius. Thanks!

**Comment by nelsonic** [comment]
@sean-hill glad I could help. 
please ⭐ the repo if you find it useful (*to help others find it too...*)
thanks! 👍

**Comment by sean-hill** [comment]
@nelsonic done!
