### ISSUE TITLE
Is there a way to change an object stored in a token or to re-state the token without becoming unauthenticated

### ISSUE THREAD

**Issue by naazy** [dwyl/hapi-auth-jwt2#171]
I have a sessions object for a user with the following keys: email, value, session_id, user_id and roles where roles contains a key value pair of a certain event and the user's corresponding event `{1: 'ADMIN', 2: 'ANON'}` . This is store in a JWT token in a cookie.

I want to update the roles object within session to `{1: 'ADMIN', 2: 'ANON', 3: 'ADMIN'}` , and save it as a JWT in a cookie. However, I am having problems when I try to state the token again. I have also tried unstating the previous token and re-stating the new one but this is causing authentication problems too. What is considered best practice for this kind of behaviour?

Thanks

**Comment by nelsonic** [comment]
@naazy / @roryc89 the answer is *Yes*! 
I will take a look at your code this evening. 👍

**Comment by naazy** [comment]
Thanks @nelsonic!

**Comment by nelsonic** [comment]
@naazy I *believe* you got to the bottom of this issue... can you update with a quick paragraph?

**Comment by naazy** [comment]
This is how we did it:

```
 var session= request.auth.credentials;
session.roles[3]='ADMIN';
 var token = JWT.sign(session, process.env.JWT_SECRET); 
reply().state('token', token, { path: '/' }).redirect('/dashboard');
```

Note we had to set the cookie to the path that the initial cookie was set on - otherwise we were ending up with 2 different token cookies for different paths!

**Comment by nelsonic** [comment]
@naazy this is _fantastic_ and worth adding to the FAQ section of the Readme ... https://github.com/dwyl/hapi-auth-jwt2#frequently-asked-questions-faq- 😉

**Comment by nelsonic** [comment]
We can _close_ this now as @naazy has kindly added the solution to the readme. 👍
