### ISSUE TITLE
difference between auth of jwt and oauth 2.0?

### ISSUE THREAD

**Issue by pablocarreraest** [dwyl/hapi-auth-jwt2#176]
I was searching for a plugin for oauth 2.0 for an API project (im newbie in hapi) in that process I get confuse on jwt auth and oauth 2.0 (http bearer token). it seems that is the same but with some adjustments or can anyone can clarify...

thanks

**Comment by nelsonic** [comment]
@pablocarreraest are you considering writing your own OAuth _Provider_...?

**Comment by nelsonic** [comment]
@pablocarreraest OAuth 2 is a "_authorization flows for web applications_" https://oauth.net/2/
Auth0 are using JWTs in their OAuth flow. But they are separate and independent concepts. 
Please read: https://github.com/dwyl/learn-json-web-tokens
