### ISSUE TITLE
A changelog would be nice

### ISSUE THREAD

**Issue by sfabriece** [dwyl/hapi-auth-jwt2#177]
I was looking at some updates for the module but it's hard to figure out what has changed with each release.

Thanks :)

**Comment by nelsonic** [comment]
Hi @sfabriece, 
At _present_ the changes are described in release messages: https://github.com/dwyl/hapi-auth-jwt2/releases
<img width="1020" alt="hapi-auth-jwt2-releases" src="https://cloud.githubusercontent.com/assets/194400/16363721/491d43d0-3bcb-11e6-9fe2-8b035ecaec6a.png">
The _next_ time a change is required we will create a `CHANGELOG.md` 👍

**Comment by sfabriece** [comment]
I saw those. Some of them are truncated. 👍

**Comment by nelsonic** [comment]
@sfabriece I tend to keep the release info quite minimal, but will expand the description and include a link to the PR from now on. thanks!
