### ISSUE TITLE
Issues with request.auth

### ISSUE THREAD

**Issue by dhershman1** [dwyl/hapi-auth-jwt2#181]
So I am pretty new to json web tokens, and I've ran into a little snag. my request.auth object never really updates once I use a login. I generate a token, send it through the authorization header, and I even save it as a cookie. All of these happen and go great however, the request.auth never actually updates, I still get false for isAuthenticated and null for the rest. Perhaps I am doing something wrong?

My auth strategy gets set like so:

```js
server.auth.strategy('jwt', 'jwt', true, {
		key: process.env.JWT || 'itsasecretsecret-',
		validateFunc: function(decoded, request, cb) {
			r.table('accounts').filter(r.row('id').eq(decoded.id.id)).run(conn, (err, cursor) => {
				cursor.toArray((err, results) => {
					if (!results.length) {
						return cb(null, false);
					}
					return cb(null, true);
				});
			});
		},
		verifyOptions: { algorithms: ['HS256'] }
	});
```

I am using rethinkdb which is what `r` and `conn` are for.

**Comment by nelsonic** [comment]
Hi @dhershman1 where are you setting the cookie in your handler?
is your code on GitHub? (or can you paste a bit more detail?)
thanks!

**Comment by dhershman1** [comment]
Sorry for the late reply, my manual login function runs like so:
```js
validatePassword(pass, result[0].pass, function(err, res) {
						let token = createToken(result[0]);
						if (res) {
							reply.state('user', result[0].user, {
								ttl: 86400000,
								parse: true
							});
							if (request.payload.remember_me) {
								reply.state('pass', result[0].pass, {
									ttl: 86400000,
									encoding: 'base64json',
									parse: true
								});
							}
							reply({ token: token })
							.header('Authorization', token)
							.state('token', token, cookie_options)
							.redirect('/');
						} else {
							reply('invalid-password');
						}
					});
```

**Comment by dhershman1** [comment]
Still not able to see what exactly I am doing wrong that's preventing the authentication from being updated.

**Comment by dhershman1** [comment]
Turns out validation is working, however only when authentication is required so if I set a route to have an auth value of false, the isAuthenticated is also set to false, etc. However if I go to a page that has auth set to jwt, it DOES set this value. I am a tard.
