### ISSUE TITLE
Sync > Async (decode > verify)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#188]
At present we are using `JWT.decode` https://github.com/dwyl/hapi-auth-jwt2/blob/07252726ea2cd0b4b19f8de0d9a0c3ee06fe636a/lib/index.js#L61

It's probably not _necessary_ anymore given that we are _also_ calling [`JWT.verify`](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) a few lines later: https://github.com/dwyl/hapi-auth-jwt2/blob/07252726ea2cd0b4b19f8de0d9a0c3ee06fe636a/lib/index.js#L79 

Do we _need **both**_ ?

**Comment by nelsonic** [comment]
Closing this issue as no one else has "_complained_" about having a "_blocking_" method in the plugin. Our benchmarks indicate that we can run `JWT.decode` ***20k times per second*** so not really a _bottleneck_ ... if someone has a worse "_performance_" experience, please re-open so we can investigate further. 👍

**Comment by GEEKIAM** [comment]
@nelsonic thank you for this benchmark. I was looking for information about JWT.decode due to it synchronous implementation and found this issue :)

**Comment by nelsonic** [comment]
@GEEKIAM yeah, if you need a more _detailed_ benchmark let us know! 👍
