### ISSUE TITLE
Using JWT via URI

### ISSUE THREAD

**Issue by carlskii** [dwyl/hapi-auth-jwt2#19]
Hi,

I need to configure HAPI to accept the JWT via the URI as part of a GET request. Is it possible to use it in this way? 

Regards.

**Comment by nelsonic** [comment]
Hi @carlskii 
The URI use-case is not implemented (*yet*) as it encourages people to share URLs with tokens (which *can* lead to security compromise) but... we would consider a Pull Request if you want to submit one...

**Comment by nelsonic** [comment]
What would you want to *call* the URL parameter? 
e.g. `token` or `jwt` ?

**Comment by nelsonic** [comment]
@carlskii we can implement this in no time. please just let us know what url parameter you want to use. thanks.

**Comment by carlskii** [comment]
I guess it could just be called "token".

The use case for me would be to ideally generate a time expiring key or token to some of my routes. A bit like Amazons S3 signed url feature. Not sure though if JWT is the right thing for this though.

**Comment by nelsonic** [comment]
Using the exp (expiry) time stamp in the JWT you can easily reject a token that has expired.
Are you hoping to send the link in an email?

**Comment by carlskii** [comment]
Yes that's the plan.

**Comment by nelsonic** [comment]
Ok, do you have time to help us write some code or documentation for the feature?

**Comment by carlskii** [comment]
I can help document it, but my skills with regards writing the code for this type of thing are limited.

**Comment by rainabba** [comment]
What is the status on this issue? Is this project maintained (no reply since April 22 on the issue)?

**Comment by nelsonic** [comment]
@rainabba thanks for reminding us about this! This module is maintained and *actively* used. 
We have *just* published a new version of the module to npm which allows tokens to be passed in via url parameter.
Please let us know if you need any help getting started with using it. :+1:

**Comment by nelsonic** [comment]
@carlskii we have released `Version 4.6.0` which includes support for `token` url parameter.
Closing this issue as we consider it to be resolved by the latest release.
Let us know if you need anything else! :+1:

**Comment by rainabba** [comment]
Much appreciated!

**Comment by nelsonic** [comment]
@rainabba we appreciate you keeping us on our toes! :wink: 
please :star: the repository to signal to others that you find it useful. 
Thanks again! :+1:

**Comment by alexdrans** [comment]
Just needed this feature, thanks feature requesters of times past!

**Comment by nelsonic** [comment]
@alexdrans yeah, we're _lucky_ that way...! ❤️  
(_hope you are well and your project(s) are going smoothly!_)
