### ISSUE TITLE
No error thrown if validateFunc is supplied but 'key' is omitted.

### ISSUE THREAD

**Issue by asilluron** [dwyl/hapi-auth-jwt2#191]
`if(options.key && typeof options.validateFunc === 'function') {`

This check fails but prompts an error related to verifyFunc.

**Comment by nelsonic** [comment]
@asilluron can you give us a bit more code? is `options.key` `undefined` or `null` ?

**Comment by asilluron** [comment]
I was hoping I could get a PR in quickly, but to give you more details it
was undefined.

**Comment by nelsonic** [comment]
@asilluron sounds like we could use an additional check to see if there is at least one key.
if you have time for a quick PR please go for it thanks! 👍

**Comment by bitcloud** [comment]
as elaborated on #226 perhaps validateFunc could also be optional if the jwtwebtoken checks are sufficient.

also currently it is not documented that if you supply both, a verifyFunc and a validationFunc, the verifyFunc is completely ignored.

**Comment by nelsonic** [comment]
@asilluron thanks for opening this issue. Hopefully it is resolved now. 👍
