### ISSUE TITLE
Why set the toke in the headers and as a cookie?

### ISSUE THREAD

**Issue by JMurphyWeb** [dwyl/hapi-auth-jwt2#197]
> reply({text: 'You have been authenticated!'})
.header("Authorization", token)        // where token is the JWT 
.state("token", token, cookie_options) // set the cookie with options 

I was wondering why you would want to set it in both?

**Comment by nelsonic** [comment]
@JMurphyWeb _great_ question. _Just_ use the `.state()` (_i.e. cookie_) 👍

**Comment by JMurphyWeb** [comment]
like a native mobile app I guess?

**Comment by nelsonic** [comment]
Exactly. In _most_ situations Cookies are a better choice. But if your Backend is used as an API (Hapi's original purpose) then Headers are the only option. 👍
