### ISSUE TITLE
Unknown authentication strategy jwt

### ISSUE THREAD

**Issue by anttilinno** [dwyl/hapi-auth-jwt2#198]
Good day.

I'm trying to run hapi, glue and jwt2. I found the example mentioned in FAQ, but I'm still not getting it to run. I have a prototype with 2 modules: auth and pinger(which replies pong). If I remove auth: 'jwt', server works, but no auth is required. If I add auth, I get error 
```
Error: Unknown authentication strategy jwt in /pinger
```

auth/index.js
```
'use strict'

const hapiJwt = require('hapi-auth-jwt2')
const JWT_SECRET_KEY = '12345'

const register = function register (server, options, next) {
  server.register(hapiJwt)
  server.auth.strategy('jwt', 'jwt', true,
  { key: JWT_SECRET_KEY,
    validateFunc: (decoded, request, callback) => callback(null, true), // This should be replaced with a more robust function
    verifyOptions: { algorithms: [ 'HS256' ] }
  })

  server.auth.default('jwt')
  next()
}

register.attributes = {
  name: 'auth-wrapper',
  version: '0.0.1'
}

module.exports = register
```

pinger/index.js
```
exports.register = (server, options, next) => {

    server.route({
        path: '/pinger',
        method: 'GET',
        config: { auth: 'jwt' },
        handler: require('./pinger')
    });

    next();

};

exports.register.attributes = {
    pkg: {
      "name": "pinger",
      "version": "1.0.0"
    }
};
```

manifest.js
```
const Config = require('./config');

// Glue manifest
const manifest = module.exports = {

    server: {
        app: Config.app,
    },

    connections: [
        {
            host: Config.server.host,
            port: Config.server.port,
        },
    ],

    registrations: [
        {
            plugin: 'hapi-knex-objection-builder',
            plugin: './auth',
            plugin: './pinger'
        },
    ],

};

if (process.env.NODE_ENV === 'dev') {
    manifest.server.debug = {
        log: ['error', 'implementation', 'internal'],
        request: ['error', 'implementation', 'internal'],
    };
    manifest.registrations.push({
        plugin: {
            register: 'blipp',
        },
    });
}

if (process.env.NODE_ENV === 'production') {
    manifest.registrations.push({
        plugin: {
            register: 'poop',
            options: Config.poop,
        },
    });
}
```

And server, src/index.js
```
import { assert } from 'hoek';
import { compose } from 'glue';
import Labbable from 'labbable';
import Manifest from './config/manifest';

const labbable = module.exports = new Labbable();

const options = {
  relativeTo: __dirname + '/lib/modules'
};

compose(Manifest, options, (err, server) => {

    assert(!err, err);

    // Pass server along to labbable
    labbable.using(server);

    server.initialize((err) => {

        assert(!err, err);

        // No need to start server if this is being required (i.e. for testing)
        if (module.parent) {
            return;
        }

        server.start((err) => {

            assert(!err, err);

            console.log(`Server started at ${server.info.uri}`);
        });
    });
});
```

If config is needed, I can provide it. I have a feeling, that the auth plugin is not loaded. Anyway, this issue drives me up the wall. I could integrate the auth in the main file, but I don't want to :)

Can someone point me to a right direction? 😆

**Comment by sikancil** [comment]
Got same error! 

**Glue** `v4.0.0`.
**Hapi** `v15.1.1`.
**hapi-auth-jwt2** `v7.1.3`

@nelsonic or anybody.. you may take a look also on my gist here:
https://gist.github.com/sikancil/71f0c07d699cdbe248c243e48913fbbf
`file: server.js`
`line: 244`

**Comment by sikancil** [comment]
### Update:
When I tried using **Glue** defined with **only 1 (one) connection** in my gist, it's working.
`server.js` `line: 13 ~ 29` 
and place  **`comment /* */`**  at `line: 22 ~ 28`,

results as below:
```javascript
manifest: {
	connections: [
		{  host: 'sikancil.dev',  port: 9810,  labels: [ 'io' ]  }
	],
	registrations: [
		{  plugin: 'inert',  options: {  select: [ 'io' ]  }  },
		{  plugin: 'hapi-auth-jwt2',  options: {  select: [ 'io' ]  }  },
		{  plugin: 'yar',  options: {  select: [ 'io' ]  }  }
	]
}
```

I already tried in pure HapiJS by re-write another code without **Glue**,
and returned as same, if got **more than 1 (one) connection**.

Previously, about 2 months ago, I had successful ran `hapi-auth-jwt2` in pure `HapiJS` with multiple connections (2); not even using `Glue`. 
**Node** `v4.5.0`
**Hapi** `v14.2.0`
**hapi-auth-jwt2** `v5.2.0`

**Comment by anttilinno** [comment]
Hm, I have only single connection 😄 Although it is defined in array.

**Comment by sikancil** [comment]
@anttilinno have you try this way (for your case) ?
`File: auth/index.js`
```javascript
const register = function register (server, options, next) {
  //-- server.register has a callback, which might better to put server.auth.strategy on it
  server.register(hapiJwt, (err) => {
    if (err) { console.log('(X) hapi-auth-jwt-2 registration failed!'); }
    server.auth.strategy('jwt', 'jwt', true,
      {
        key: JWT_SECRET_KEY,
        validateFunc: (decoded, request, callback) => callback(null, true), // This should be replaced with a more robust function
        verifyOptions: { algorithms: [ 'HS256' ] }
      }
    );

    server.auth.default('jwt');
    next();
  });
}

**Comment by sikancil** [comment]
### Update:
IMHO, I think this is not for `hapi-auth-jwt2` plugin issue.

I had tried in several different simulations, which return as `Glue` logic problem, then I tried on pure Hapi code, to get better minimalistic code .

1.  Require `hapi` module
2.  Create [`new Hapi.Server()`](http://hapijs.com/api#new-serveroptions)
3.  Define [`server.connections()`](http://hapijs.com/api#serverconnectionoptions)
4.  Register [`Hapi-Plugins`](http://hapijs.com/api#plugins) into each [`connections`](http://hapijs.com/api#serverconnectionoptions) by using [`server.register()`](http://hapijs.com/api#serverregisterplugins-options-callback)
  - and if you were under the [`Glue`](https://github.com/hapijs/glue) in my understanding that it doesn't have an `event` to patch some `method` or `function` to define some sub-process after current plugin registered from [`server.register()`](http://hapijs.com/api#serverregisterplugins-options-callback) as `callback(err)` [L163](https://github.com/hapijs/hapi/blob/master/lib/plugin.js#L163) [L301](https://github.com/hapijs/hapi/blob/master/lib/plugin.js#L301) [L324](https://github.com/hapijs/hapi/blob/master/lib/plugin.js#L324) before the `next(err)` tick process. [L119](https://github.com/hapijs/glue/blob/master/lib/index.js#L119) imho..
  - When you were implement [`auth.strategy()`](http://hapijs.com/api#serverauthstrategyname-scheme-mode-options) on multiple connections, you will need to define from [`connection.auth.strategy()`](https://github.com/hapijs/hapi/blob/master/lib/auth.js#L38), and for single connection may call from [`server.auth.strategy()`](https://github.com/hapijs/hapi/blob/master/lib/auth.js#L38), which implement from [`auth.scheme()`](http://hapijs.com/api#serverauthschemename-scheme).
  - And I think it should better to call after the plugin registered and before call the `next(err)` tick process. [L119](https://github.com/hapijs/glue/blob/master/lib/index.js#L119) imho..
5.  You may double-check if your preferred plugins on each connections, are they already registered by fetch it on [`server.registrations`](https://github.com/hapijs/hapi/blob/master/lib/server.js#L45) for single connection or [`connection.registrations`](https://github.com/hapijs/hapi/blob/master/lib/connection.js#L66) for multiple connection.
6.  Register [`Hapi-Routes`](http://hapijs.com/api#serverrouteoptions) by call `server.route()` for a single connection, or may call from `connection.route()` from instance of multiple connections to define right into each connections.
7.  Start the `server` by call [`server.start()`](http://hapijs.com/api#serverstartcallback)

A lot to taken, but it's better to code pure in Hapi for several cases.

**Comment by anttilinno** [comment]
Thank you for your effort. Seems, that glue is not the answer to all the prayers. I will try and re-structure my code without glue.

**Comment by anttilinno** [comment]
Ok, turns out I was registering plugins wrong. So, nothing wrong with glue or jwt2.

Correct way:
```
    registrations: [
        {
           { plugin: 'hapi-knex-objection-builder' },
           { plugin: './auth' },
           { plugin: './pinger' }
        },
    ],
```

Incorrect way:

```
    registrations: [
        {
            plugin: 'hapi-knex-objection-builder',
            plugin: './auth',
            plugin: './pinger'
        },
    ],
```

This n00b error cost me many hours and endless frustration :) Maybe it will shine some light to someone, who has somehow made same mistake.
