### ISSUE TITLE
Per Route Parameter That Can Be Read by Validation Function 

### ISSUE THREAD

**Issue by mashaalmemon** [dwyl/hapi-auth-jwt2#200]
Hi There,

I am wondering if there is a way to specify a configuration variable for a route that can be read by the validateFunc in context of the specific route. I'll try to explain my use case:
- My JWT has user specific route permissions encoded in it (imagine a permission of "A" for add, "U" for update, "D" for delete).
- I would like to have one of the same permissions associated to each route (again  "A" for the add route, "U" for update route, "D" for delete route).
- Once the JWT is verified as true and not expired, I need to check what the route permission needed to give access to the route (lets say "A") and if the user has that same permission as show in their JWT data (in this case "A"), I consider validation to be successful. Otherwise validation has failed.

Ultimately I am not clear on, and need a way to:
1. Label each route with a permission that can be read by the validation function.
2. When validating, get access to the route label/permission for the route being hit (so either route awareness or simple access to the label/permission is required).

Any way to accomplish this in a straightforward way with Hapi?

**Comment by mashaalmemon** [comment]
Hi There,

Circling back on this I read up on hapi[scopes](https://blog.andyet.com/2015/06/16/harnessing-hapi-scopes/).

I've changed my approach slightly. What I do now is have the validateFunc determine ALL the accessible scopes by reading the jwt and pass it back through the callback (note this is typescript but javascript users should get the idea):

```ts
function jwtValidate(decodedJWTData: AdminJWT, request:Request, callback:Function): void
    {
        // if token could not be decoded, we have unauthorized access
        if (!decodedJWTData.sub) {
            debug("Unauthorized Access");
            return callback(null, false); // if value not found, not valid token
        }
        // otherwise access in so far as JWT validity is granted
        else {
            // build scopes this user has
            var userScope:string[] = AdminAuth.buildUserScopeArray(decodedJWTData);
            // userScope might be ['A', 'U'] as the user has add/update permissions
            // value found so token valid
            return callback(null, true, {scope: userScope});
        }
    }
```

Then I let the hapi scopes functionality see if the scopes for the route match or not by specifying valid scope conditions per route:

```ts

routes = [
   ...
   // user must have scope 'A' to access this route
   { method: "GET", path: "/get/url",
            config: { auth: {
                        strategies: [jwt-strategy],
                        scope:['A']},
                handler: getAllUsers}},
   ...
   ]
```

Hopefully someone will find this useful.

**Comment by nelsonic** [comment]
@mashaalmemon thanks for this code sample. 👍
