### ISSUE TITLE
Support multiple keys?

### ISSUE THREAD

**Issue by gangstead** [dwyl/hapi-auth-jwt2#205]
I'm looking to support multiple valid keys for a request.  In most cases a user would only have 1 valid key, but when a key is deprecated they could still use both for a period of time.

This can be done with a small code change https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L82 so that the key passed in (or key returned by the key lookup function) can optionally be an array of keys to check.  A 401 would only be returned if `JWT.verify` fails for all keys.

I'm willing to do the work for this: code change, new tests, documentation update (anything else?).  I just want to make sure this fits in with the road map for this plugin.  I don't want to do all the work and find out it's never going to be merged.

**Comment by nelsonic** [comment]
@gangstead, thanks for getting in touch to make this request. Yes, there's no _reason_ we would _not_ want to have multiple keys in an `Array`...
(_apologies for taking `forever` to respond. each time I try to look a this PR someone distracts me with "work"..._)

**Comment by nelsonic** [comment]
@gangstead `v7.2.0` is now on NPM with your changes. again, apologies for the delay. Thanks for your contribution & welcome to DWYL! ❤️  ✅  🎉

**Comment by nelsonic** [comment]
@gangstead please close the issue once you've confirmed that it's working as desired/expected. 👍

**Comment by gangstead** [comment]
Updated my project and added some tests and it's working as expected.  Thanks!
