### ISSUE TITLE
Need an example of an endpoint that generate the token

### ISSUE THREAD

**Issue by bdavidxyz** [dwyl/hapi-auth-jwt2#207]
Let's say that the server will have a single page app as a client.

The basic example show 2 endpoints :

"/" that doesn't require a token
"/restricted" that require a token

Is it possible to add a simple example of a route, say "/create" or "/register" that will create the token for the frontend app ?

Example of how Knock handles it in the Rails world : https://github.com/nsarno/knock#authenticating-from-a-web-or-mobile-application

**Comment by nelsonic** [comment]
Hi @bdavidxyz good question (_thanks for asking_), let's understand your _requirements_ a little further... Do you want the `user` of your app to _authenticate_ before being able to access the `/restricted` endpoint? or do you simply want to assign them a token `automatically` when they start using the app regardless of whether they have "logged in"?

**Comment by bdavidxyz** [comment]
Good question. I'm in the most classical scenario where there will be a login page, a register page, and somewhere a logout button once authenticated. Therefore, I would choose option 1) I want my user to be able to authenticate before being able to access to the `/restricted` endpoint. But I also need the ability to register, which mean automatically assign a token if the user does not already exist in database.

**Comment by bdavidxyz** [comment]
In addition, this snippet could do the job, what do you think ?
```    
{
      method: "POST", path: "/user_token", config: { auth: false },
      handler: function(request, reply) {
        // var user = serviceThatPersistUserAndEncrytedPassword(request.params)
        var token = JWT.sign(user, secret);
        reply({jwt: token});
      }
}
```

**Comment by nelsonic** [comment]
@bdavidxyz that _could_ valid option. _however_ in our projects we tend to attach the `token` as `.state` on the response. 
e.g: [`github.com/dwyl/hapi-login-example-postgres/lib/handlers/login_handler.js#L45`](https://github.com/dwyl/hapi-login-example-postgres/blob/acf3797dcfa1efb82a3667c3c040fb004270a9ba/lib/handlers/login_handler.js#L45)

So your handler would be:
```js
{
  method: "POST", 
  path: "/login", 
  config: { auth: false },
  handler: function(request, reply) {
    // var user = serviceThatPersistUserAndEncrytedPassword(request.params)
    var token = JWT.sign(user, secret);
    return reply.view('personal-dashboard', {
      user: user
    }).state("token", token);
  }
}
```

> ***Next question***: *how* are you building your `client` ("`SPA`") ?

**Comment by cfey** [comment]
Thanks for the answer, I'm new to JWT as well and missed that part.
Maybe you can add a part to the readme

What I noticed is, that when I want to give the SPA frontend the token via a header (`authorization`), I need to add `.state("token", token);` to the reply.
Else my generated token is different from the token in the cookie

**Comment by atrauzzi** [comment]
Based on this scenario, where to I obtain/create the JWT?  Any specific libraries?

**Comment by nelsonic** [comment]
@atrauzzi did you see: https://github.com/dwyl/learn-json-web-tokens
and the simple example: https://github.com/dwyl/hapi-auth-jwt2-example ?

**Comment by nelsonic** [comment]
3 years later. No reply from OP. Guessing no longer an issue. Closing. 👍
