### ISSUE TITLE
how to refresh the expiration time of token in every request

### ISSUE THREAD

**Issue by rssandy1991** [dwyl/hapi-auth-jwt2#209]

**Comment by asabzposh** [comment]
Create a new token with the updated "expiresIn" value. And send back that token.

**Comment by shai32** [comment]
is it not a bad performance to do that?
creating a token can be time consuming for each request?

**Comment by roytz** [comment]
@asabzposh , is there a way doing that within the `validate` function?

**Comment by bitcloud** [comment]
check #237 for an possible solution.

**Comment by nelsonic** [comment]
indeed this can easily be done in the `validate` function.
As noted by @bitcloud, please see #237 for more detail.
Thanks.
