### ISSUE TITLE
Unable to use errorFunc 

### ISSUE THREAD

**Issue by Jiropole** [dwyl/hapi-auth-jwt2#218]
I'm trying to return a 503 rather than 401 under certain conditions. It looks like that's what `errorFunc` is used for, but when I define it, it causes the request to hang and never complete. Probably it's user error, but could use some help.

I originally raise the error in `verifyFunc`:
```
        callback(Boom.serverUnavailable(ApiConstants.errorCodes.apiUnavailable), false);
```
A define `errorFunc`:
```
        errorFunc: function (context) {
            if (context.message.message == ApiConstants.errorCodes.apiUnavailable) {
                context.errorType = Boom.serverUnavailable;
                context.message = context.message.message;
            }
            return context;
        }
```
This gets called, and I set the **required** fields according to the docs, but then no response is sent. Thanks for the help!

**Comment by Jiropole** [comment]
Oh, hm. Then I saw #77, which implies `errorFunc` is not necessary, and we can just return 503 error, yet (with the above code) this still replies with 401 error. I'm surely missing something...

**Comment by nelsonic** [comment]
@Jiropole thanks for this issue. glad you saw #77 and figured it out. The plugin has been comprehensively updated as has the Hapi framework. If anyone still has issues with `errorFunc` please open a new issue. Thanks.
