### ISSUE TITLE
request.payload data extraction fails for POST requests in validateFunction

### ISSUE THREAD

**Issue by asabzposh** [dwyl/hapi-auth-jwt2#219]
I require the user to enter his/her email address when they are logging in. Then I need to pull up their accounts with the associated email address to check JWT; if I try to extract any data from 'request.payload' in the validateFunc, I get "null".

But I am able to extract information from 'request.payload' if I wait for my execution to reach the route.

My server auth strategy setup is as follows:

```
server.auth.strategy('jwt', 'jwt', {
        key: privateKey,          // Never Share your secret key
        validateFunc: validate,            // validate function defined above
        verifyOptions: { 
            ignoreExpiration: true, 
            algorithms: algo, 
            issuer: issuer 
        },
        complete: true
    });
```

My validate function looks like the following:

```
var validate = function(decoded, request, callback){        
    console.log(request.payload['email']);
    Tokenizer.validateToken(decoded, request, UserModel, function(err, isValid){        
        return callback(err, isValid);      
    });
}
```
The documentation for hapi-auth-jwt2 says that the following:

> request - (required) is the original request received from the client

If I switch my routes to a GET request instead of POST and try to pass the email as a parameter then I can access it via request.query.

**Comment by hchhatbar** [comment]
I am facing the same issue, I need to get the email from the payload but it returns null. Unfortunately, I cannot use GET. Any suggestions on how to access the payload in the validate function?

**Comment by slaawwa** [comment]
@hchhatbar, I duplicate this package and add this functionality in my repository https://github.com/slaawwa/hapi-auth-jwt2-payload and npm package https://www.npmjs.com/package/hapi-auth-jwt2-payload
Try maybe it help

**Comment by bitcloud** [comment]
@slaawwa why duplicating instead of making a pull request? And why did you not just fork?

**Comment by hchhatbar** [comment]
@slaawwa - thanks! 
how did you solve this issue? Are you able to access the payload within the validate function?

**Comment by slaawwa** [comment]
Hi,
1) @bitcloud, I doesn`t know good my solution or not.
@hchhatbar 
This package can not check post data because method payload run after, but extract function do exception if not find token and authorize return error. So, I check if we dont have token and request make with method post then return 'tryPOST' in credentials. And after that in payload method, I check if credentials equal 'tryPOST' run first function. BUT NOW This function have POST! So it is work. But I think some try programer find more good solution or it is correct work?

**Comment by jaredramirez** [comment]
+1 on needing the payload in `validateFunc`

**Comment by hfwittmann** [comment]
I have recently submitted a pull request (very simple) that addresses this issue

https://github.com/dwyl/hapi-auth-jwt2/pull/240
