### ISSUE TITLE
Support: What would be the proper way of calling a protected route from within the server?

### ISSUE THREAD

**Issue by Dindaleon** [dwyl/hapi-auth-jwt2#220]
Hello,

I would like to know how can I call a protected route from within the server and bypass the authentication?

I was thinking about creating a master authentication key, store it in the server as a global variable, and whenever I need to call a protected route from within the server, I give it the master key. Is this ok, or is not safe?

**Comment by vdeturckheim** [comment]
In my understanding of your question, you might want to check [`inject`](https://github.com/hapijs/hapi/blob/master/API.md#serverinjectoptions-callback) which can be used to make internal calls to a server. According to the doc, if a `credentials` claim is passed in the  `option`object, auth is bypassed.

**Comment by Dindaleon** [comment]
Very nice, I will try that. Thank you.
