### ISSUE TITLE
Homepage example stops working with recent packages

### ISSUE THREAD

**Issue by carlok** [dwyl/hapi-auth-jwt2#222]
Hello, here you can find you "homepage" example, with just a basic "export" of the routes.
Using these packages

`"hapi": "13.5.0", "hapi-auth-jwt2": "7.0.1"`

it works, while using these packages

`"hapi": "16.1.0", "hapi-auth-jwt2": "7.2.4"`

it does not work (Error: Unknown authentication strategy jwt in...)

The code is at [this gist](https://gist.github.com/carlok/33e5a22705b641507d3b5182852375cd).

As you can see, it is basically your example.
How to refactor it?
Thanks.

**Comment by ubirajaramneto** [comment]
Try removing `config: {auth: 'jwt'}` on line 41 and change this:

`server.auth.strategy('jwt', 'jwt', {
        key: 'NeverShareYourSecret',          // Never Share your secret key
        validateFunc: validate,            // validate function defined above
        verifyOptions: {algorithms: ['HS256']} // pick a strong algorithm
});`

into this:

`server.auth.strategy('jwt', 'jwt', true { <--- only change is to add true as a third argument
        key: 'NeverShareYourSecret',          // Never Share your secret key
        validateFunc: validate,            // validate function defined above
        verifyOptions: {algorithms: ['HS256']} // pick a strong algorithm
});`

Maybe I could shed some light to the issue here, at least the "Unknown authentication strategy jwt" error disappeared.

**Comment by carlok** [comment]
I suppose you mean adding "true," (just "true" breaks syntax) but with "true," (and removing line 41) it breaks too.

**Comment by ubirajaramneto** [comment]
yes, correct, ill edit accordingly, thanks for the correction.

but I do not understand how removing the auth key in the config object breaks it, can you give more details?

The restricted route should look like this:

`{
            method: 'GET',
            path: '/restricted',
            handler: function (request, reply) {
                reply({text: 'You used a Token!'})
                    .header("Authorization", request.headers.authorization);
            }
}`

**Comment by carlok** [comment]
I saved the version of the previous gist according to your changes.
It is at
https://gist.github.com/carlok/4e33063ce7b0de3176bd19b5b532ff70
the restricted route is the same as yours and there is the "true," in server.auth.strategy but here it says 
`throw new Error(msgs.join(' ') || 'Unknown error');
    ^
Error: Cannot set default strategy more than once`

(different but stil broken)

Did you try the previous gist? Please try with this new one. The package.json should be the same as in the firsr post of this thread. Thank you.

**Comment by ubirajaramneto** [comment]
I believe this part of the documentation can shed some light to the issue:

`// setting the 3rd argument to true means 'mode' is 'required' see: http://hapijs.com/tutorials/auth#mode
server.auth.strategy('jwt', 'jwt', true, { // so JWT auth is required for all routes
  key: process.env.JWT_SECRET,
  validateFunc: require('./jwt2_validate_func'),
  verifyOptions: { ignoreExpiration: true, algorithms: [ 'HS256' ] }
});`

On the docs this section can be found at https://github.com/dwyl/hapi-auth-jwt2#how-do-i-set-jwt-auth-to-all-routes

When you pass the third argument as true on the configuration of the auth strategy, it already registers that as a default, try removing the following from your gist:

server.auth.default('jwt');

Let me know if that works or not.

**Comment by carlok** [comment]
Hi, I created a new, now working gists with comments (httpie client: cleanear than curl) on its head with link to the docs and this thread.
It is at
https://gist.github.com/carlok/599443aebbfad8312dd5294c48ab9d31
This is almost the same example of the homepage of the project but this one is working with the recent versions so I'd suggest to update the example according to this one (or a variant) also according to the links you pointed me out to.
Thank you so much for your help.

**Comment by ubirajaramneto** [comment]
You are welcome, I'm glad I could help.

**Comment by nelsonic** [comment]
Example has been updated for latest Hapi using `asycn/await`.
If anyone still has any issues running the examples, please open a new issue.
Thanks. 👍
