### ISSUE TITLE
How to make pre-authorization on POST file upload with multipart/form-data

### ISSUE THREAD

**Issue by dunnock** [dwyl/hapi-auth-jwt2#223]
Hello, I am using this package:

`"hapi-auth-jwt2": "^7.1.2"`

With default setup (please see below) authorization on POST file upload happens after file was uploaded to the server, while it might happen once headers received not loading server with useless file upload. Is there any way to achieve that? Thank you!

```
  server.auth.strategy('jwt', 'jwt', 'required', {
    key: secret,
    verifyOptions: { algorithms: [algorithm] },
    validateFunc: (decoded, request, callback) => {
```

**Comment by nelsonic** [comment]
@dunnock to _clarify_ are you wanting to _authenticate_ the person _after_ they have initiated the uploading of the file?

**Comment by dunnock** [comment]
@nelsonic thanks for quick answer, no, but we don't force user to close application and token might expire at the time when upload started

**Comment by nelsonic** [comment]
This is a valid use case and we would accept a PR with tests to add it. 
Given the age of this issue (4 years) I'm guessing it's no longer needed.
Closing. 👍
