### ISSUE TITLE
request.auth.artifacts as an object instead of token string

### ISSUE THREAD

**Issue by genadis** [dwyl/hapi-auth-jwt2#224]
Hello,

In my use case I need to use the request.auth.artifacts to store additional data in the request flow.

It would be great if the token that is currently saved as string directly on `request.auth.artifacts ` would be stored in a object:
```
request.auth.artifacts = {
   token: ....
}
```

this would allow extending the artifacts with additional data by the application.

I'm aware that I could use request.auth.credentials, and I do use it for other stuff. The data I want to store belongs more to `request.auth.artifacts`

Thanks!

**Comment by ozum** [comment]
How can we add data to `request.auth.artifacts`, as OP pointed out?
