### ISSUE TITLE
Mix recaptcha & hapi-auth-jwt2

### ISSUE THREAD

**Issue by MacTheZazou** [dwyl/hapi-auth-jwt2#225]
Hey, I know this is not the best place to ask this question, but:

Is there an easy way to combine a Recaptcha verification with the JWT one? Like using two auth scheme for one path?

I would like to do a pre-verification for jwt and for a Recaptcha token for some path. Before executing any other code.

Do I have to fork & modify the hapi-auth-jwt2 plugin, or there is a more convenient way?

Thank you in advance!

**Comment by nelsonic** [comment]
@MacTheZazou are you using a Hapi.js Server? which plugin for Recaptcha are you using (_or do you have in mind_) ?

**Comment by MacTheZazou** [comment]
Right now, i'm using hapi with hapi-auth-jwt2
To check the recaptcha token, I just do a post HTTPS request with the
request module.

I would like to be able to just set the auth to 'accessJWTAndRecaptcha' for
example. And Hapi check both before executing the handler.

Is there any way to achieve that?

Thank you!

**Comment by nelsonic** [comment]
@MacTheZazou there is _always_ a way of achieving. 
I would _suggest_ that you write a _custom_ `validateFunc` that calls the Recaptcha service if the payload includes something you want to verify with the 3rd party service.

**Comment by MacTheZazou** [comment]
@nelsonic That's brilliant! I'm using hapi-auth-jwt2 for a such long time that I forget about the `validateFunc`!

Thank you for your incredible work at Dwyl!

**Comment by nelsonic** [comment]
@MacTheZazou any time. let us know if you manage (_or need any help_) to get it  working. ❤️  ✅
