### ISSUE TITLE
debug option for verbose/semi-verbose logging?

### ISSUE THREAD

**Issue by randallbpotter15** [dwyl/hapi-auth-jwt2#227]
It would be great to be able to pass a debug parameter to troubleshoot JWT issues.
For example targeting this file and bit of code:

_/lib/index.js: line 149_
```
          keys.some(function (k) { // itterate through one or more JWT keys
            JWT.verify(token, k, verifyOptions,
              function (verify_err, verify_decoded) {
                if (verify_err) {
                  keysTried++;
                  if (keysTried >= keys.length) {
                    return reply(raiseError('unauthorized',
                      'Invalid token', tokenType), null, { credentials: null });
                  }
```
I'm able to trace out what might be caught in the 'verify_err' object versus the standardized language in the reply.  This was very helpful in troubleshooting key issues.

**Comment by nelsonic** [comment]
This is a good idea. detailed debugging capability is always useful. 
If anyone wants to open a Pull Request to add it, please go for it!
