### ISSUE TITLE
Question about the key we set on the strategy (public/private key)

### ISSUE THREAD

**Issue by roytz** [dwyl/hapi-auth-jwt2#228]
Hi,
As I understand from your example, the secret key I use when creating the 'jwt' strategy is my private key which I use to encode the data I transfer to the client and then to decode it when I get it back.
What I don't understand is how does the client knows that the token he got is correct and that he got it from the server without anyone tempering it on the way? Is there a public key the client uses to check that the token he got is correct?

Thanks

**Comment by shai32** [comment]
Does anyone know, How can I decode the token in the client?

**Comment by nelsonic** [comment]
@roytz I'm not _sure_ I _understand_ your question, 
is it related to `hapi-auth-jwt2` or JTWs in _general_...?

Yes, the **secret key** used to encode the JWT is _only_ known to the server.
In most cases, the client does not check the token.
The client _receives_ the JWT from the Server and then sends the JWT _back_ to the server
and the _server_ checks if the JWT was signed using the **secret key**.

@shai32 your question does not _appear_ to relate to the original question posted by @roytz ... 🤔 
If you want to decode JWTs on the client use a library like: https://github.com/auth0/jwt-decode

**Comment by roytz** [comment]
@nelsonic , thank you for the detailed answer.
So it means that the client doesn't check the token at all and just make sure he gets one? I though that the client should use it when the user navigates between pages to make sure the user is still connected and show him the page (assuming that I don't get the pages from the server but from the client).

@shai32 , please open a different thread for your question and I'm sure you'll get an answer.

**Comment by shai32** [comment]
ֿ?

**Comment by tamias** [comment]
The example is using a single secret key, rather than a public/private key pair.

If you want to use a public/private key pair, you would sign the JWT with the private key, and pass the public key in the call to call `server.auth.strategy`.  This approach makes it possible to verify the signature in the client without exposing your private key.

See the documentation for [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) for more info.

**Comment by nelsonic** [comment]
@tamias answered this question/thread. 🥇 
No follow up. Guessing resolved. Closing. ✅
