### ISSUE TITLE
`algorithms` option should be coupled to the `key` (when using as array)

### ISSUE THREAD

**Issue by dominykas** [dwyl/hapi-auth-jwt2#231]
At the moment, there is a single `algorithms` option, but it is possible to set up multiple keys. It might make sense to couple the `algorithms` option with the `key`, because public key should only ever be used with `RS***` as protection against the vulnerability as described in [this blog post](http://blog.websecurify.com/2017/02/hacking-json-web-tokens.html). There is already built in [protection in `jsonwebtoken`](https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js#L72), but it requires the `algorithms` option to not be set at all.

The use case is auth0 migration - their older `/oauth/ro` endpoint returns a JWT signed with a shared secret (`HS256`), whereas the newer `/oauth/token` returns a JWT signed with a private key (`RS256`). To securely configure the app, `algorithms` field _must_ be left empty (rather than configured to allow both - `RS256` and `HS256`).

Happy to PR, if there's an agreement on the approach - I'd vote banning `key` as an array (breaking change), and require an explicit array of `credentials: [{ key, algorithms }]` when using multiple keys is desirable (or change the 4th param to `strategy` to allow array?).

**Comment by dominykas** [comment]
Sorry to bug you... but any guideline would be great. I'm happy to PR any fix we can agree upon!

**Comment by nelsonic** [comment]
PR always welcome. Please re-open if you have time to add. Thanks.
