### ISSUE TITLE
Extend token expiration

### ISSUE THREAD

**Issue by roytz** [dwyl/hapi-auth-jwt2#233]
Hi,
I've set the token `exp` value to be `7d`.
Now, I want to extend the expiration every time the token is being validated and expires in less than 7 days - I want to do that on the `validateFunc`.
Here is my `validateFunc` with the TODO part where I want to change the exp value or return a new token with new exp value -
```
const validate = async (decoded, request, callback) => {
    try {
      // doing stuff to check that the user is valid 


      const tokenExpirationDate = moment(decoded.exp * 1000);
      if (tokenExpirationDate.diff(moment(), 'days') < 7) {
        //TODO: extend token expiration
      }
      return callback(null, true);
    } catch (error) {
      throw error;
    }
  };
```
How can I do that?

**Comment by doron2402** [comment]
you'll have to generate a new token and pass it to the user.
JWT token are immutable

**Comment by roytz** [comment]
Thank you @doron2402 , can I generate a new token and pass it back to the client from the validate function (since this is the place where I find out if a token expired)?

Regarding the Redis solution, what do you mean by it will help me restrict access without changing the secret key?

**Comment by doron2402** [comment]
np @roytz,


for your first question, you can return the new token inside the header and make sure to use it on the client. if you have some sort of a middle layer between your api you can force the `Authorization` header to be equal to the new value.

For your second question regarding Redis, JWT token have a life time lets say a week. and lets say that some how your token got leaked or someone hack your user computer and now holds the JWT token. there's no way for you to restrict this token even if you delete the user from your database and change the user password.
Therefore you can use redis and validate the token against it.

**Comment by roytz** [comment]
thanks @doron2402

**Comment by shai32** [comment]
In the validate function, I don't have a way to return a new token.
so how can I send a new token to the client?

**Comment by doron2402** [comment]
you can overwrite the validate function to return a callback/promise with the token.
your handler should handle the response (reply object). It's a bad practice to have your validate function have access to the request & reply objects

**Comment by shai32** [comment]
1. you can't pass along extra fields with [validateFunc](https://github.com/dwyl/hapi-auth-jwt2#documentation), you can only call callback with errr, valid and  credentials:
callback - (required) a callback function with the signature function(err, isValid, credentials) where:
err - an internal error.
valid - true if the JWT was valid, otherwise false.
credentials - (optional) alternative credentials to be set instead of decoded.
2. all my api calls should have this logic to return the new token when expierd. so adding this logic to every handler is a bad practice.

handling renew expiration is mandatory and basic.
how do you guys, solve it?

**Comment by bitcloud** [comment]
did my answer in #237 solve this issue for you?

**Comment by shai32** [comment]
yes

**Comment by bitcloud** [comment]
great! what about you @roytz? otherwise you can close this issue. :-)

**Comment by roytz** [comment]
Thanks @bitcloud
