### ISSUE TITLE
How set custom response. 

### ISSUE THREAD

**Issue by SergeyJyravlev** [dwyl/hapi-auth-jwt2#234]
Hello. 
Please maybe help me. 
I build REST API with hapi.
How I can set custom response for failed checkout token?

the response now
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Invalid token format",
  "attributes": {
    "error": "Invalid token format"
  }
}

Need change to 

{
  error: {
      code: 401,
      message: 'Invalid token format'
}

**Comment by Nargonath** [comment]
Check out the optional parameter `errorFunc`: https://github.com/dwyl/hapi-auth-jwt2#optional-parameters

**Comment by nelsonic** [comment]
Closing as no response from OP in 3 years. Thanks @Nargonath for the useful link. 🥇
