### ISSUE TITLE
access token / refresh token

### ISSUE THREAD

**Issue by ricktbaker** [dwyl/hapi-auth-jwt2#238]
We're considering moving from mean.io and oauth, over to hapi and jwt.   I'm trying to get up to speed on this move, and i'm curious if this module supports refresh tokens as well, or if I'm just looking at a move that is more difficult than I am expecting.

**Comment by ricktbaker** [comment]
Went with our own method of refresh tokens

**Comment by craigtaub** [comment]
Hi @ricktbaker 
Did you find a straight-forward way to implement refresh tokens with `hapi-auth-jwt2`?
