### ISSUE TITLE
how to decorate fetch header

### ISSUE THREAD

**Issue by J0NNYZER0** [dwyl/hapi-auth-jwt2#245]
Hi nelson or shai32,
We are getting 401 status on all services decorated with auth jwt in hapijs. I figured this might be to do with how my team and I are making our fetch call in our reactjs api. Without going to deep into our codebase here is a snippet of code which works when jwt2 auth is turned off. Is there anything additional we might be missing in the fetch api call or something which we need to change?

```
class CourseApi {
  static getAllCourses(session) {
    return new Promise((resolve, reject) => {
      const url = `${serverConstants.courses.GET_COURSES}`; // this/is/some/path/to/service
      fetch(url, {
         method: 'GET',
         headers: session, credentials: 'same-origin'
       }).then(function(response) {
        if (response.status >= 400) return reject(response.status);
          return response.json();
      })
      .then(function (data) {
        resolve(data.data ? data.data : data);
      })
    });
  }
```

Thanks and finger are crossed for a simple solution.

**Comment by nelsonic** [comment]
@J0NNYZER0 _how_ are you sending the JWT (token) to the server? (_is it a cookie or a header_)

**Comment by J0NNYZER0** [comment]
I am sending it in the header like so: 
'Accept': 'application/json',
           'Content-Type': 'application/json; charset=utf-8',
           'Authorization': 'this is some encrypted token'

**Comment by J0NNYZER0** [comment]
@nelsonic - any update as to if we are doing this right?

**Comment by ricmalta** [comment]
@J0NNYZER0 I manage to solve that by using the options.responseFunc.

**Comment by nelsonic** [comment]
@J0NNYZER0 provided you're sending the JWT through in the `Authorization` header (_as you've described_) and you're following the docs to use the JWT2 plugin, it should work. 👍

**Comment by nelsonic** [comment]
@J0NNYZER0 yeah, the responseFunc would be a good approach, @ricmalta is spot on. 👍

**Comment by J0NNYZER0** [comment]
@nelsonic - I have never used the responseFunc so can you please share a simple implementation of how I could use it?

**Comment by ricmalta** [comment]
@J0NNYZER0 this is my handler:

```javascript
// if the status is an error, set the proper status code
const handleResponse = (request, reply) => {
  return request.authz.statusCode >= 400
  ? reply(Boom.create(request.authz.statusCode))
  : reply.continue()
}
```

The authz is a second prop I am using in the request  object to handle the authorization (not authentication).
This module is meant to handle only the authentication, and to responde 401 without an authorization verification is valid.

Another way to solve your problem is to create a hapijs responde plugin like this:

```javasript
exports.register = (server, options, next) => {
  server.ext('onPreResponse', (request, reply) => {
    if (request.response instanceof Error && config.app.logging) {
      if (request.response && request.response.output && request.response.output.statusCode < 500) return reply.continue()
      log.error(request.response)
    }

    reply.continue()
  })

  next()
}
```
However, this one is just to throw the HTTP 500 to the log. But you could use it to handle every kind of > 400 status.

**Comment by J0NNYZER0** [comment]
@ricmalta - Thanks for the swift reply. If @nelsonic agrees that this is the best way to handle then I will go ahead and install it assuming it works for me.

**Comment by nelsonic** [comment]
@ricmalta  looks really good. (_not a "hack"_)
@J0NNYZER0 keep us posted with your progress. 👍

**Comment by J0NNYZER0** [comment]
Stay tuned. I will attempt this tomorrow morning. Fingers crossed on this. I will let you both now if I have questions.

**Comment by J0NNYZER0** [comment]
@ricmalta - About to implement your handler with the authz property. How are you setting the authz variable? Can you provide a basic implementation of that since this variable is important? Thanks!

**Comment by ricmalta** [comment]
@J0NNYZER0 the authz variable is irrelevant. 
You need to have a way to handle your own HTTP status, in order to know which status you will return to the client in the responsFunc function.

I bet you will find the right place in your code.

However, this is simply how I set the authz variable:

```javscript
let ok = methods[method] === true
request.authz = { userId, service, entity, geolocations, statusCode: ok ? 200 : 403 }
```
This is part of my private authorization code.

**Comment by J0NNYZER0** [comment]
So I am wondering how exactly what I need to decorate my headers with in order to pass through the 401 - 
Here's my super basic configuration below for jwt2. Do you see anything funny with it?

  server.auth.strategy('jwt', 'jwt', true, {
    key: process.env.SECRET_KEY,
    responseFunc: (request, reply) => {
      console.log('responseFunc: ', request.response)
      reply.continue()
    },
    validateFunc: (decoded, request, callback) => {
      return callback(err, true)
    },
    verifyOptions: { ignoreExpiration: true }
  })

**Comment by J0NNYZER0** [comment]
FYI - using the above configuration it doesn't seem like responseFunc is being hit with the console log.

**Comment by J0NNYZER0** [comment]
An easier fix for me was setting the headerKey and set the header in the client request.

**Comment by J0NNYZER0** [comment]
Thanks @nelsonic and @ricmalta for sticking by me. If either of you are going to next weeks node conference in SF i can get you a drink as a thanks!

**Comment by nelsonic** [comment]
This thread appears to have been resolved. 
Thanks again @J0NNYZER0 & @ricmalta 👍  
Closing.
