### ISSUE TITLE
default unsecured access

### ISSUE THREAD

**Issue by walshe** [dwyl/hapi-auth-jwt2#246]
is there a way to have all paths by default unsecure, so that I don't have to add mode:'try' to every path in my app ?

**Comment by ricmalta** [comment]
@walshe You should use only the Hapi configuration, not Hapi-JTW2 module.

Just use this Hapi configuration to have optional authentication (validates if present):

```javascript
server.auth.strategy('jwt', 'jwt', 'optional', {  key: config.auth.secret,  validateFunc: handleCheck,  verifyOptions: {  algorithms: [ 'HS256' ]  } })
```

See this: https://hapijs.com/tutorials/auth#mode

**Comment by nelsonic** [comment]
@walshe hopefully the answer posted by @ricmalta clarified things for you.
If you still have any issues, please open a new issue. Thanks.
