### ISSUE TITLE
Not compatible with Hapi 17.*

### ISSUE THREAD

**Issue by murbanowicz** [dwyl/hapi-auth-jwt2#248]
Hi,
It is not working with Hapi 17.*.
At least `'name'` is missing, but may be some more issues.

**Comment by nelsonic** [comment]
@murbanowicz _thank you_ for opening this issue. 
Hapi V.17 has _not_ been released yet. There is a "_Release **Candidate**_" so people can `try` it.
We are _waiting_ for the v.17 Release Notes: https://github.com/hapijs/hapi/issues/3658 
As soon as the "Upgrade Path" notes are finalised we will do the work to upgrade our Plugin(s) and release a new ***major*** version to NPM.

**Comment by BorntraegerMarc** [comment]
@nelsonic v17 has been released now 😄

**Comment by alexisohayon** [comment]
Anything new regarding the v17?

**Comment by rmeltonmi** [comment]
As a temporary resolution (not a production fix),  I was able to resolve the error by adding 

exports.name = 'hapi-auth-jwt2';  

to the index.js file  within the module package: lib/index.js

**Comment by unicodeveloper** [comment]
Any news regarding the v17? @nelsonic  

It needs to be upgraded to support v17

**Comment by rayhaanq** [comment]
Any news with this?

**Comment by microcipcip** [comment]
Anyone waiting for this, it seems that there is a [working fork here](https://github.com/dwyl/hapi-auth-jwt2/pull/249#issuecomment-350432038) waiting to be merged in...

**Comment by rodrigokieffer** [comment]
Hapi 17.2 was released. 
Any prediction of when the merge or adjustments will be made?

**Comment by mshick** [comment]
This is the main blocker for me going to v17. Would love an update.

**Comment by microcipcip** [comment]
@mshick [this works 100%](https://github.com/dwyl/hapi-auth-jwt2/pull/249#issuecomment-350432038) with Hapi 17.

**Comment by teemuniiranen** [comment]
Upgrading from 16.x to 17.2 caused following Hapi AssertionError:
```
[ 'AssertionError [ERR_ASSERTION]: Authentication strategy jwt uses unknown scheme: jwt',
     '    at module.exports.internals.Auth._strategy (/data/app/node_modules/hapi/lib/auth.js:49:14)'
```
Seems like Hapi 17 is requiring scheme registration with server.auth.scheme function:
https://github.com/hapijs/hapi/blob/master/API.md#authentication-scheme

Have some one got it working?

**Comment by microcipcip** [comment]
@teemuniiranen see my comments, you need to install the fork

**Comment by murbanowicz** [comment]
This is not how it should be.
The changes should be merged so npm will have it already

**Comment by microcipcip** [comment]
Well, if you want to use it _today_ that's the easiest way of doing it. They are [working on it](https://github.com/dwyl/hapi-auth-jwt2/issues/258#issuecomment-356445558).

**Comment by Kuchiriel** [comment]
Its not working with me.
**"hapi": "^17.5.4",**
**"hapi-auth-jwt2": "^8.1.0",**

**Comment by Kuchiriel** [comment]
Hi @murbanowicz  I've downgraded and tested the deps one by one and I've managed to make it work. I will comment here for anyone with the same issue after upgrading hapi.js and hapi.js plugins.

* "blipp": "^2.3.0",
* "boom": "^5.2.0",
* "good": "^7.2.0",
* "good-console": "^6.4.0",
* "good-squeeze": "^5.0.2",
* "hapi": "^16.5.2",
* "hapi-auth-jwt2": "^7.3.0",
* "hapi-cors": "^1.0.1",
* "hapi-postgres-connection": "^6.2.0",
* "joi": "^10.6.0",

The problem seens to be, the newer versions of hapi.js and newers plugins don't work properly with es2018 code style.
