### ISSUE TITLE
Should we add the methods set() and clear() like hapi-auth-cookie?

### ISSUE THREAD

**Issue by poeticninja** [dwyl/hapi-auth-jwt2#25]
My favorite auth plugin for Hapi at the moment is hapi-auth-cookie for how easy it is to get setup.  I can setup my settings with the plugin, in a route I can use `request.auth.session.set()` to authenticate a user and `request.auth.session.clear()` if I want to remove the users authentication.

I am wanting to start using JSON Web Tokens but there seems to be more work for the same amount of steps. I am thinking the developer interface to this plugin could be a little more like hapi-auth-cookie and it would welcome more people to use it. I like the idea of where you are going and I could easily see this being THE auth plugin for hapi that everyone goes to.

I am hoping you take this as constructive and as me seeing ways it could improve. It is already freaking awesome. :smile:

**Comment by nelsonic** [comment]
@poeticninja we've been thinking the same (improving the ease-of-use). Do you have time to elaborate on how we could implement? (or even submit a PR...?)

**Comment by poeticninja** [comment]
@nelsonic I have listed out below a few features that would make it easy for developers to use.

1. Do not require a developer to use the validate function. Have a built in method that has a good standard and then in the options provide a way to supply their own validate function. hapi-auth-cookie does this. Instead of jsonwebtoken it uses the iron module to encrypt.

2. With step 1 done then a user wont need to require jsonwebtoken but just pass in a secret key into the plugin options.

(So far we have eliminated two steps but still keeping the same functionality.)

3. In the plugin options a developer should be able to pass in jsonwebtoken properties that they want on all users (expiresInMinutes, issuer, etc).

3. We would hook into the hapi lifecycle request of `onPreAuth` to add new methods to request.auth.session. These methods would allow a dev to .set(user) or .clear() a users encryption key from the cookies.

I would like to hear your thoughts on the above changes.

**Comment by nelsonic** [comment]
Nice.

**Comment by poeticninja** [comment]
I would like to do a pull request but I wont be able to at the moment. Me doing a pull request depends on how things go with my current projects. (I am trying to play catch up at the moment.)

**Comment by nelsonic** [comment]
@poeticninja we are also behind on our deadline... :cry: 
As soon as you have time let us know, we'd *love* to collaborate with you! :+1:

**Comment by devinivy** [comment]
:+1: this would be great.  If I find some free time, I'll see if I can help out with a PR.

**Comment by devinivy** [comment]
Thinking more about this– what exactly do you all imagine `set` and `clear` would do?  It's definitely less obvious compared to hapi-auth-cookie.  Perhaps an exposed method to create signed JWTs with the secret and algorithm provided would be enough.  I'm especially unclear about `clear` (:P) because JWTs typically expire organically after a certain time period, but can't be forced to expire without some extra data-backed mechanism, or cooperation with the client to throw away old tokens.

**Comment by nelsonic** [comment]
Gents, this feature would still be *nice-to-have*...
If you have time to work on it, please re-open this issue and/or submit a PR. thanks! :+1:
