### ISSUE TITLE
How to make Authentication header not required?

### ISSUE THREAD

**Issue by Dindaleon** [dwyl/hapi-auth-jwt2#251]
Hello,
I want to pass my httpOnly cookie to the server.

I know the format is as follows:
`headers: {
    Authorization: 'token=' + myToken
}`

How do I get `myToken` if it is encrypted inside a httpOnly cookie?

**Comment by nelsonic** [comment]
@Dindaleon did you see: https://github.com/dwyl/hapi-auth-jwt2#want-to-sendstore-your-jwt-in-a-cookie ?

**Comment by nelsonic** [comment]
3 year old question answered but no follow up. Closing.
