### ISSUE TITLE
Invalid register options "value" must be an object

### ISSUE THREAD

**Issue by rayhaanq** [dwyl/hapi-auth-jwt2#254]
I'm getting a strange error `Invalid register options "value" must be an object` whenever I try to run my hapi server. I can't seem to figure out the issue. This is my code:

```
await server.register(require('hapi-auth-jwt2'), (err) => {
            if (err) console.log(err);

            server.auth.strategy('jwt', 'jwt', {
                key: secretKey,
                verifyOptions: { algorithms: ['HS256'] }
            });

            glob.sync('api/**/routes/*.js', {
                root: __dirname
            }).forEach(file => {
                const route = require(path.join(__dirname, file));
                server.route(route);
            });
        }).catch(err => {
            console.log(err);
        });
```
I've also tried this and I'm still getting the error:

```
const options = {
            key: secretKey,
            verifyOptions: { algorithms: ['HS256'] }
        };

await server.register({
            register: require('hapi-auth-jwt2'),
            options
        }, (err) => {
            if (err) console.log(err);
            // We're giving the strategy both a name
            // and scheme of 'jwt'
            server.auth.strategy('jwt', 'jwt', {
                key: secretKey,
                verifyOptions: { algorithms: ['HS256'] }
            });

            glob.sync('api/**/routes/*.js', {
                root: __dirname
            }).forEach(file => {
                const route = require(path.join(__dirname, file));
                server.route(route);
            });
        }).catch(err => {
            console.log(err);
        });
```
Does anyone have any idea what this error is about? Is it just that `hapi-auth-jwt2` is not up to date with Hapi v17? If so I've tried changing my dependency version to `salzhrani/hapi-auth-jwt2#v-17` as mentioned in https://github.com/dwyl/hapi-auth-jwt2/pull/249

I've also tried the temporary fix in https://github.com/dwyl/hapi-auth-jwt2/issues/248 with no luck.

**Comment by rayhaanq** [comment]
This works with promises but not async/await

**Comment by serranoarevalo** [comment]
@rayhaanq  Hey, you can see this pull request https://github.com/dwyl/hapi-auth-jwt2/pull/249 (that hasn't been merged) where it's updated for v17.

**Comment by alfredomp** [comment]
@rayhaanq I think you are missing a validation function in the options. See assert here, in the olde version, (https://github.com/dwyl/hapi-auth-jwt2/blob/f2560e65548a7763433fbe599dca39b5eb175ce6/lib/index.js#L68) and in the #249 (https://github.com/rocky-jaiswal/hapi-auth-jwt2/blob/7ff04c040a8553319fed2fa9675fda4b602f9400/lib/index.js#L55)

**Comment by skimi** [comment]
Lots of breaking changes with hapijs v17.
Hapijs is now promise based. So I think the register fn should return a promise instead of calling `next()` and the plugin structure has been changed.

[v17 release note](https://github.com/hapijs/hapi/issues/3658)

Personally reverted to hapijs v16.6.2 for now.

**Comment by nelsonic** [comment]
The plugin has been updated to work with `async/await`. This should no longer be an issue. Closing. 👍
