### ISSUE TITLE
JSHint is Out-of-Date with Latest Node.js Syntax

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#264]
Our `jshint` check is _woefully_ out-of-date with the "Modern" way of writing JS/Node.js code.
![image](https://user-images.githubusercontent.com/194400/36683497-9fa59f38-1b15-11e8-9773-1c4c4e6a5595.png)

I propose that we _re-think_ it. 
@roryc89 / @naazy / @finnhodgkin / @SimonLab / @Conorc1000 / @Cleop 
& anyone `else` _interested_ in JS Style ... please share your thoughts. (_thanks!_)

**Comment by finnhodgkin** [comment]
I moved to eslint with Prettier on all my personal projects. 

After using elm with elm-format for a while, I found that whenever I jumped back to JavaScript I really missed having opinionated auto-formatting. Prettier provides this in an even stricter format than elm-format (line length is forced), and integrates with project eslint rules.

I'm not sure if there's similar integration with jshint, but it doesn't seem to be provided by default in prettier-atom.
