### ISSUE TITLE
No longer using "GoodParts" (linting) due to "modern" JS

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#266]
Sadly, we are no longer using "Good Parts" in our JS due to Hapi.js using "Modern JS" i.e. "async await" ...
https://github.com/dwyl/goodparts

So I'm _considering_ removing it as a `devDependency` and "badge" from the repo. 
(_to avoid any confusion for people ..._)
thoughts?

**Comment by salzhrani** [comment]
I agree. I had a PR with eslint + prettier if you think it is a good idea

**Comment by nelsonic** [comment]
@salzhrani if you have time to do a PR updating the linting, please go for it! 👍

**Comment by nelsonic** [comment]
`eslint` used in `package.json`: https://github.com/dwyl/hapi-auth-jwt2/blob/ecb5dd358d0cf34c277364943f29553d1c839c9d/package.json#L103-L104

Closing. 👍
