### ISSUE TITLE
Misleading documentation for jsonwebtoken parameters

### ISSUE THREAD

**Issue by SimonSchick** [dwyl/hapi-auth-jwt2#267]
In the docs https://github.com/dwyl/hapi-auth-jwt2#optional-parameters the parameters appear to have an entirely different meaning than the ones from the actual jsonwebtoken repo (https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback).

Imo the docs should be entirely removed and replaced with just a link..

**Comment by nelsonic** [comment]
The Optional Parameters refer to the options accepted by `hapi-auth-jwt2` in verifying a request.
They are not the same as those in the underlying `jsonwebtoken`. 
This is not suggested or implied. 
Closing.
