### ISSUE TITLE
Readd support for promises in responseFunc

### ISSUE THREAD

**Issue by ethanrubio** [dwyl/hapi-auth-jwt2#271]
In `hapi-auth-jwt2 `version <= 7, responseFunc functions that returned promises used to work due to passing a callback that could be innvoked after promises have settled. https://github.com/dwyl/hapi-auth-jwt2/blob/91111ce184afa2871d49d8a027f91ae92ad2b2ed/lib/index.js#L219-L240

In this package's current form, async functions are not supported because promises are never returned. https://github.com/dwyl/hapi-auth-jwt2/blob/cd8f0ff4fa6ee09016452349cfee93b8c957bf69/lib/index.js#L228-L246

I propose that this package add back support for this functionality.

**Comment by nelsonic** [comment]
@ethanrubio thanks for opening this issue to discuss the `Promises` requirement. 
We don't tend to use them in our code and since we didn't have a test for them, 
we didn't realise that the functionality had been "_removed_". 

Happy to "re-add". 
Thanks. 👍

**Comment by nelsonic** [comment]
@ethanrubio `hapi-auth-jwt2@8.1.0` on NPM contains your addition/update. thanks again! 🥇

**Comment by ethanrubio** [comment]
awesome - I'll close the issue now since the changes have been merged in! thanks!
