### ISSUE TITLE
responseFunc hangs

### ISSUE THREAD

**Issue by hassanshaikley** [dwyl/hapi-auth-jwt2#273]
When I add an empty responseFunc it hangs and a reply to the client is not sent. 

ie 

````const responseFunc = () => {
}```

version `7.3.0` & `7.4.0`

**Comment by nelsonic** [comment]
@hassanshaikley please share a more detailed code example. 
![image](https://user-images.githubusercontent.com/194400/38302177-ac21b98a-37f9-11e8-99c9-9a5bfcf57194.png)
This is insufficient for us to help "diagnose" the issue ... 🤔

**Comment by nelsonic** [comment]
Without any additional info we are unable to diagnose this issue.
Given that this question was opened 3 years ago and the package has since been comprehensively updated, I get the feeling this is no longer an issue. Please re-open if still required. Thanks.
