### ISSUE TITLE
Not working with file uploads(multipart formdata)

### ISSUE THREAD

**Issue by hussainb** [dwyl/hapi-auth-jwt2#274]
**Registering the plugin:**

```
    await server.register(require('hapi-auth-jwt2'));
    server.auth.strategy('jwt', 'jwt',
        {
            key: tokenSecret,
            validate: async (decoded, request) => {
                return { isValid: true }
            },
            verifyOptions: { algorithms: ['HS256'] }
        });

    await server.register({
        plugin: require('hapi-routes'),
        options: {
            dir: `${__dirname}/app/routes/*`,
        },
    });

```

**Route Configuration:**

```
export { }

import uploadCtrl from '../controllers/uploadCtrl';

const routes = [{
    method: 'POST',
    path: '/upload',
    options: {
        payload: {
            output: 'stream',
            allow: 'multipart/form-data', // important
            maxBytes: 100000000
        },
        auth: 'jwt'
    },
    handler: uploadCtrl
}];

exports.routes = (server: any) => server.route(routes);

```

**POST response with a file:**

![image](https://user-images.githubusercontent.com/4962633/39227297-84cea7e4-4875-11e8-8f3a-fbdfedbecb5b.png)

**POST response without a file (expected similar response for POST with the file):**

![image](https://user-images.githubusercontent.com/4962633/39227328-af8b2a52-4875-11e8-989d-d69e4e0d9313.png)

**Dummy authorization header used for the above:**

![image](https://user-images.githubusercontent.com/4962633/39227375-e8377cac-4875-11e8-904f-d6a8b7ff66ef.png)

**No errors/warnings/info generated by Hapi in the console below for both the cases:**

![image](https://user-images.githubusercontent.com/4962633/39227465-5f1da6a2-4876-11e8-8f01-b12dd6e9df28.png)

I am not able to figure out if I am missing something or if there is some other issue.

**Comment by stefan-c** [comment]
You’re sending gibberish as the Authorization header value, that’s why you’re getting an invalid token format error. You need to supply a valid token in the auth header. You can use [jsonwebtoken.sign()](https://github.com/dwyl/hapi-auth-jwt2#usage-1) or [this tool](https://jwt.io/) to generate/sign your tokens.

**Comment by hussainb** [comment]
@stefan-c , yeah I understand that I am sending gibberish as the Auth header.. I did that for some initial testing..
My question is why the difference when adding a file to the POST call.
I believe that the server should have returned "Invalid token format" as response even for the POST with file.

**Comment by hussainb** [comment]
@stefan-c 
Yes the server was running when I sent the first request.
I am just toggling the file checkbox in postman and the response varies.

My code is similar to yours.
Below is the simplified version which doesn't work for me while doing a file post.

**server.ts**

```
import * as Hapi from 'hapi';
import * as Boom from 'boom';
import * as path from 'path'
import * as fs from 'fs';
import * as loki from 'lokijs';

import { tokenSecret } from './app/controllers/authCtrl';

// Create a server with a host and port
const server = new Hapi.Server({
    host: 'localhost',
    port: 8000
});

const registerPlugs = async () => {

    await server.register(require('hapi-auth-jwt2'));
    server.auth.strategy('jwt', 'jwt',
        {
            key: tokenSecret,
            validate: async (decoded, request) => {
                return { isValid: true }
            },
            verifyOptions: { algorithms: ['HS256'] }
        });

    await server.register({
        plugin: require('hapi-routes'),
        options: {
            dir: `${__dirname}/app/routes/*`,
        },
    });

    // Add the route
    server.route({
        method: 'GET',
        path: '/hello',
        handler: function (request, h) {
            return 'hello world';
        },
        options: { auth: 'jwt' }
    });

    console.log("plugins registered")
}




// Start the server
async function start() {
    await registerPlugs();

    try {
        await server.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    console.log('Server running at:', server.info.uri);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

start();
```

and since I am using the plugin `hapi-routes` 

**upload.ts**

```
export { }

import uploadCtrl from '../controllers/uploadCtrl';

const routes = [{
    method: 'POST',
    path: '/upload',
    options: {
        payload: {
            output: 'stream',
            allow: 'multipart/form-data', // important
            maxBytes: 100000000
        },
        auth: 'jwt'
    },
    // handler: uploadCtrl
    handler: () => 'ok'
}];

exports.routes = (server: any) => server.route(routes);
```

**Comment by hussainb** [comment]
@stefan-c ,

hey, I added `debug: { request: ['error'] }` as mentioned at [hapi logging](https://hapijs.com/tutorials/logging)

It now displayed the error `Debug: auth, unauthenticated, error, jwt` on the console! 
don't know why it doesn't respond with the error in the API response.
It somehow works different for normal vs file posts.

Closing the issue.
Thanks for your assistance!
