### ISSUE TITLE
configure with glue

### ISSUE THREAD

**Issue by supun19** [dwyl/hapi-auth-jwt2#278]
I am using glue with hapi. I set up the as bellow.

`const internals = {};
const people = { // our "users database"
    1: {
        id: 1,
        name: 'Jen Jones'
    }
};

// bring your own validation function
const validate = function (decoded, request) {

    // do your checks to see if the person is valid
    if (!people[decoded.id]) {
        return { isValid: false };
    }
    else {
        return { isValid: true };
    }
};

internals.applyStrategy = function (server, next) {
    server.auth.strategy('token', 'jwt',
    { key: 'NeverShareYourSecret',          // Never Share your secret key
        validate: validate,            // validate function defined above
        verifyOptions: { algorithms: [ 'HS256' ] } // pick a strong algorithm
    });

    server.auth.default('jwt');

    next();
};

exports.register = function (server, options, next) {

    server.dependency(['hapi-auth-jwt2'], internals.applyStrategy);

    next();
};

exports.register.attributes = {
    name: 'auth'
};
`
The problem is the server started without error but cannot go to any route. can you help me

**Comment by nelsonic** [comment]
This question refers to an older version of `Hapi` and the plugin.
If you are still having trouble using the plugin with `Glue` please open a new issue with your specific challenge. 
Thanks.
