### ISSUE TITLE
How to use with Third-party authentication plugins

### ISSUE THREAD

**Issue by mjafarpour** [dwyl/hapi-auth-jwt2#279]
Hi, 
Can use this plugin with Hapi Bell for Third-party authentication in SPA web pages?
Bell mechanism is based on redirect to new page, this method is not use in SPA web pages.

**Comment by Jerome1337** [comment]
@mjafarpour Did you find a solution to your problem?

**Comment by nelsonic** [comment]
This question is not strictly relevant to the plugin.
Please see: https://hapi.dev/tutorials/auth
