### ISSUE TITLE
Can't Destroy JWT

### ISSUE THREAD

**Issue by shivam8800** [dwyl/hapi-auth-jwt2#281]
I don't know is there any way of deactivate a jwt token when user loggedout.
since 2 months I did not get any possible way of doing it.
Can anyone help me ?
My server configuration are below:-

```
const validate = async function (user,decoded, request) {
    // checks to see if the person is valid
    if (!user["_id"]) {
      return { isValid: false };
    }
    else {
      return { isValid: true };
    }
};
await server.register(require('hapi-auth-jwt2'));

    server.auth.strategy('jwt', 'jwt',
      { key: process.env.SECRET_KEY,
        validate:validate,
        verifyOptions: { algorithms: [ 'HS256' ] }
      });
```
`
At the time of login I am issuing jwt token from

`const token = JWT.sign(user.toJSON(), process.env.SECRET_KEY); ` 

Now I want to destroy that issued token 
I am using hapi 17 with hapi-auth-jwt2 package 
Please give me solution with code so that I can implement it .

**Comment by nelsonic** [comment]
JWT invalidation is not part of this plugin. 
For more details please see the StackOverflow thread shared by "ghost": https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens

Thanks.
