### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Invalid register options “value” must be an object

### ISSUE THREAD

**Issue by Anirudh0509** [dwyl/hapi-auth-jwt2#282]
I am trying to setup a nodeJS application to connect a postgres DB .
Using Hapi and PostgreSQL DB.
Referred all documentations but the error persists.
While server.register

    server.register({
      register: require('hapi-node-postgres'),
      options : {
        connectionString: "Postgresdb://dbuser:dbpassword@localhost/dbName"
      }
    }, err => {
    console.log(err);
    });

The error that is coming is: 

    UnhandledPromiseRejectionWarning: ***AssertionError [ERR_ASSERTION]: Invalid register options "value" must be an object
        at Object.exports.apply*** (/home/sc/code/Reporting(proto)/node_modules/hapi/lib/config.js:22:10)
        at internals.Server.register (/home/sc/code/Reporting(proto)/node_modules/hapi/lib/server.js:367:26)
        at Object.<anonymous> (/home/sc/code/Reporting(proto)/index.js:16:8)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Function.Module.runMain (module.js:693:10)
        at startup (bootstrap_node.js:188:16)
    (node:15989) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:15989) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please assist.
I am using 
"hapi": "^17.5.3"
"hapi-node-postgres": "^4.1.0"

**Comment by colds3** [comment]
Hello,

I just encountered this error, and it seems that the register function no longer works with a callback. It seems to work with async/await. Here is my code that is working:

```
        await server.register(require('hapi-auth-jwt2'));
            
        server.auth.strategy('Bearer', 'jwt', {
            key: jwtVerification.secret,
            validate: validate,
            verifyOptions: { algorithms: [ 'HS256' ] }  // only allow HS256 algorithm 
        });
```

    "hapi": "^17.5.3",
    "hapi-auth-jwt2": "^8.1.0"

**Comment by nelsonic** [comment]
Indeed this has been updated to `async/await` as the Hapi framework has been too. Thanks.
