### ISSUE TITLE
Custom boom errors from validate function

### ISSUE THREAD

**Issue by BenMansley** [dwyl/hapi-auth-jwt2#303]
I'm aware there's a similar issue to this (#58), though I feel this is a slightly different use case so going ahead with it.

As part of our fairly simple usage of `hapi-auth-jwt2`, we have a few cases where validation fails, assuming the token is valid. After decoding the token to get a user ID, some examples of an invalid token are if the ID:
- Does not belong to a user
- Belongs to a user with an outdated token
- Belongs to a deleted user

In all of these cases a simple `{isValid: false}` object must be returned, resulting in an _Invalid credentials_ error message (status code `401` Unauthorized).
While this message is accurate for all of these cases, it would be ideal if we could customize the error message here to explain more precisely what caused the error, e.g _Deleted user_ or _Old token version_.

I believe a fairly simple improvement would be to include an optional `errorReason` string in the object returned from the `validate` function, used as the error message in the resulting Boom object.

**Comment by nelsonic** [comment]
@BenMansley sounds like a good plan. go for it! 👍

**Comment by BenMansley** [comment]
Making a PR 👍

**Comment by nelsonic** [comment]
@BenMansley `hapi-auth-jwt2@8.5.0` on NPM contains your changes. thanks again! 🥇
