### ISSUE TITLE
[Question] have to import lib folder for using hapi-auth-jwt2 or not?

### ISSUE THREAD

**Issue by tindecken** [dwyl/hapi-auth-jwt2#306]
Firstly, thank you very for making it.
I have a question while applying your project
In your example, i see you import lib folder
`const hapiAuthJWT = require('../lib/');`
then register plugin as below:
`await server.register(hapiAuthJWT);`

But in README, you use:
`  await server.register(require('hapi-auth-jwt2'));`

So what way I should use for my app?

**Comment by nelsonic** [comment]
Using an inline require statement is just a convenience. Any type of import/require statement is valid. Your choice. 👍
