### ISSUE TITLE
Add secure link to jwt.io

### ISSUE THREAD

**Issue by codeshifu** [dwyl/hapi-auth-jwt2#309]
https://github.com/dwyl/hapi-auth-jwt2#using-base64-encoded-secret-keys

The jwt.io link under the above section points to an insecure web address i.e http://jwt.io instead of https://jwt.io

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/hapi-auth-jwt2/pull/358 updates the link. ✅
