### ISSUE TITLE
Add request parameter to key method

### ISSUE THREAD

**Issue by jrpedrianes** [dwyl/hapi-auth-jwt2#312]
Would be interesting to add to the `key` method the current request, so there can be used if is necessary.

for example adding here the request and the using in the key method

`
const { keys, extraInfo } = await internals.getKeys(decoded, options, request);
`

**Comment by nelsonic** [comment]
@jrpedrianes thanks for opening this issue. 
`request` is now included. see: https://github.com/dwyl/hapi-auth-jwt2#documentation
