### ISSUE TITLE
config: {auth: false} is not work

### ISSUE THREAD

**Issue by abao1981** [dwyl/hapi-auth-jwt2#314]
it works when router path is "/register",but doesn't work when add '/user' prefix, or change path to '/user/register'

**Comment by antonsamper** [comment]
@abao1981 i'm not sure on which hapi version this changed but its no longer `config`, its now `options`. For example:

```js
server.route({
  method: 'GET',
  path: '/',
  handler: function (request, h) {
    return 'Hello World!';
  },
  options: {
    auth: false
  }
});
```

**Comment by nelsonic** [comment]
@antonsamper thanks for answering this question.
The docs/`README.md` have since been updated so hopefully this is no longer an issue.
Please re-open if still required. Thanks.
