### ISSUE TITLE
Update README.md Example With 17.x+ Compatible Code

### ISSUE THREAD

**Issue by Kyrluckechuck** [dwyl/hapi-auth-jwt2#315]
Just trying to get started with Hapi for the first time, but immediately ran into some issues trying to integrate this plugin because of the README documented basic usage example being made for versions of Hapi < 17.x

After checking out the example in `example/server.js`, I can see that the code there is compatible, and it must just be the README which is out of date.

**Comment by nelsonic** [comment]
@Kyrluckechuck thanks for opening this issue to remind us.
PR very much welcome if you have the time. 👍

**Comment by Kyrluckechuck** [comment]
Sure, I had to fork it to allow me to create the branch, but a PR is here:
https://github.com/dwyl/hapi-auth-jwt2/pull/316

**Comment by nelsonic** [comment]
PR merged. Thanks! 🌻

**Comment by rayGobel** [comment]
Hmm, I did test the code on `README.md` but the correct example was on: https://github.com/dwyl/hapi-auth-jwt2/blob/master/example/server.js#L29

**Comment by nelsonic** [comment]
`README.md` update merged. ✅ 
The code mentioned is the desired behaviour. 👍
