### ISSUE TITLE
Custom Errors with i18n Or Access to req object in errorFunc

### ISSUE THREAD

**Issue by Jeangel** [dwyl/hapi-auth-jwt2#333]
Hi, currently I'm working on an API where I have to return error messages on different languages (depending on a header...) Well, for that I decided to use [Hapi-i18n](https://www.npmjs.com/package/hapi-i18n).

Anyway, the problem I'm having right now, is that when the JWT is invalid. it returns automatically an error in english, without any way to customize it, except for the `errorFunc` method, which works pretty good.
For my case, it would be really awesome to have access to the `req` object there. So I can access to the headers and give a proper response in the respective language.

So, why I am asking here is if I can create a PR with any of these enhancements:

- Get access to the `req` object in `errorFunc` method
- The verify function can return a `Boom` error...
- Another way to return custom errors to the final client.

I would like to know if you have any advice before starting a PR, thanks in advance!

**Comment by nelsonic** [comment]
@Jeangel thanks for opening this issue. 👋 
What are you expecting to see in the headers? (_we have the main types of error covered..._)

> we are _super interested_ in the `i18n` use-case and if you are unable to make progress with the _existing_ options, we will be happy to accept a PR. We just encourage you to consider all the _existing_ options for customisation `before` modifying the  `internals.raiseError` function because it is invoked in several places and will need new tests to prevent any regressions ... 💭

**Comment by Jeangel** [comment]
Hi, thanks for quick answer! 
I'll try a couple other approaches to i18n error messages in JWT validation (Which includes expired token, invalid JWT, no JWT given).

Now, answering to your question.
> What are you expecting to see in the headers?

**R:** Sorry I was wrong, I would like to access to the `request` object in the `errorFunc` method and that way have access to `request.i18n` object stored by Hapi-i18n or any other i18n library; and be able to pass a translated message. 

Another option that comes to my mind is, if this library would provide a way to pass a `path` that aim to a `locales` folder (with help of [i18n](https://github.com/mashpie/i18n-node#list-of-all-configuration-options) of course), and internally, this library would take from those `locale-files` the error messages given a language that comes in headers, or whatever (of course, having a default english response) Maybe I'm running out of ideas 😀. But I'll give it a try.

Not sure if I'm missing something else or, haven't seen any easier way to do this. 
Anyway, I'll try to come back with a PR (Keeping in mind your advice about `internals.raiseError`)

**Comment by antonsamper** [comment]
@nelsonic Has there been any progress on this request?

My use case is that I like to remove the cookie (using `unstate`) that contains the invalid token on 401s

**Comment by nelsonic** [comment]
@antonsamper no progress as yet. We have limited availability on our end for JS work right now. ⏳ 
If anyone has time to create a Pull Request, we're happy to review and merge provided there are tests/docs. 👍

**Comment by antonsamper** [comment]
@nelsonic thanks for the prompt reply, I’ll take look 👍🏼

**Comment by nelsonic** [comment]
@antonsamper thanks again for your superb pull request #344 🎉 
`hapi-auth-jwt2@10.1.0` on NPM contains these enhancements. :shipit:
