### ISSUE TITLE
authentication alway undefined

### ISSUE THREAD

**Issue by pepatcha** [dwyl/hapi-auth-jwt2#381]
After updated from 10.2.0 to 10.4.0 my authentication function alway failed

**Comment by pepatcha** [comment]
I saw a little bug from #375 `lib/index.js` line 184 it's always mean undefined

**Comment by nelsonic** [comment]
@pepatcha thanks for opening this issue. If you don’t mind adding a bit more detail so we can try and write a regression test for this. 🙏

**Comment by pepatcha** [comment]
my bad after I tracked my code I found that is an algorithm problems.

I am using HS256 algorithm and my secret key was something like 
`-----BEGIN RSA PRIVATE KEY-----
xxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx.....
-----END RSA PRIVATE KEY-----`

It was fine when I used hapi-auth-jwt2 version 10.2.0, but after I upgraded to version 10.4.0 I got this error
`JsonWebTokenError: secretOrPublicKey must be a symmetric key when using HS256`

after I changed my key everything is fine

@nelsonic thanks for your response

**Comment by nelsonic** [comment]
@pepatcha thanks for updating. 👍 
Glad you were able to re-trace your steps and figure it out. 🔍 
And _especially_ stoked that you've confirmed that **`v10.4.0`** is working for you. 🎉 
Hope you have a great day. ☀️
