### ISSUE TITLE
Transfer repo to dwyl?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#42]
Same again.

**Comment by eventhough** [comment]
What's dwyl?

**Comment by nelsonic** [comment]
Great question @eventhough !
Where are my manners?! :anguished:
[***dwyl***](https://github.com/dwyl) is the new GitHub org for all our projects.
Everything is still 100% open source as per our Manifesto: https://github.com/dwyl/start-here/blob/master/manifesto.md so nothing will change for this or any of our other npm modules.
Everything will continue working as expected.
I have ***invited you*** to the org so you will continue to be a contributor.
Let us know if you have any other questions.
Thanks! :+1:
