### ISSUE TITLE
How to prevent access based on user's role

### ISSUE THREAD

**Issue by kenhowardpdx** [dwyl/hapi-auth-jwt2#47]
Do you have an example of how to prevent access based on the user's role?

**Comment by kenhowardpdx** [comment]
Found [this test file](https://github.com/dwyl/hapi-auth-jwt2/blob/master/test/scopes-server.js) which has exactly what I was looking for. Closing.

**Comment by nelsonic** [comment]
Sweet! :+1: 
thanks!
