### ISSUE TITLE
how to generate secret key?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#48]
> "*Apologies if this is mentioned elsewhere. The private key used for signing the tokens, is this the same as a private key generated using ssh-keygen?*"

originally posted by [@skota](https://github.com/skota) on https://github.com/ryanfitz/hapi-auth-jwt/issues/30

**Comment by nelsonic** [comment]
Hi @skota,
Since JSON Web Tokens (JWT) are not signed using [***asymmetric encryption***](http://en.wikipedia.org/wiki/Public-key_cryptography) you do not *have* to generate your secret key using ***ssh-keygen***. You can just as easily use a ***strong password*** e.g: https://www.grc.com/passwords.htm provided its ***long and random***. The chance of collision (and thus someone being able to decode your encoded JSON) is lower than the number of stars in the universe... :wink: 

We wrote a tutorial on this: https://github.com/docdis/learn-json-web-tokens  
And here's a bit more info: http://security.stackexchange.com/questions/2202/lessons-learned-and-misconceptions-regarding-encryption-and-cryptology

Hope that helps!

**Comment by skota** [comment]
Thank you. Yes it does help. Is this the right place to post questions by the way?

Thanks


________________________________

**Comment by nelsonic** [comment]
@skota glad it helped.  
there is no "right" or "wrong" place to ask questions.  
If you want them answered *fast* ask them here. :+1:

**Comment by nelsonic** [comment]
@skota we have added instructions to our readme for sourcing your JWT secret key.
Closing the issue. hope we helped.
Please re-open this issue if you need more info.

**Comment by gstolfo** [comment]
there is a correct way to generate a secret

**Comment by nelsonic** [comment]
@gstolfo please share a link to the _correct_ way, thanks! :+1:

**Comment by jdat82** [comment]
So does that mean using a private and public key is not supported by this package? If so, is it enough to read their content and provide them as the key? It seems to make jsonwebtoken crash.

**Comment by niksmac** [comment]
As seen on the `README`

```
node -e "console.log(require('crypto').randomBytes(256).toString('base64'));"
```

**Comment by oshihirii** [comment]
Just for reference as I'm learning about JWT as well, i found it interesting that i can generate a JWT token server side, send it to client to store as cookie, and then do this in browser dev tools:
     
    // returns the decoded header
    var decoded_header = JSON.parse(atob(Cookies.get("session_token").split(".")[0])); 
    
    // returns the decoded payload
    var decoded_header = JSON.parse(atob(Cookies.get("session_token").split(".")[1]));

    // returns error when trying to 'decode' the signature  
    var decoded_header = JSON.parse(atob(Cookies.get("session_token").split(".")[2]));
 
So good to know that the header and payload are just base64 encoded, so not good to store secure information in them.

**Comment by jakzal** [comment]
with openssl you can do:

```openssl rand 256 | base64```

**Comment by satishpatro44** [comment]
openssl rand -base64 10

**Comment by ben-xD** [comment]
@satishpatro44, could you explain why you use `10` for the `num` parameter of `openssl rand`? `num` is actually the number of bytes. If you only generate 10 bytes, perhaps this could be brute forced more easily? Since a threat actor can just randomly try all permutations that can be generated in 10 bytes. (i.e. If I wanted to attack your server, I can rest assured it would be easier than if you had generated e.g. 32 bytes instead)

This is just my unqualified thoughts, and I would love to see what others think about my concerns :)

**Comment by SouragAnil** [comment]
> @skota glad it helped. there is no "right" or "wrong" place to ask questions. If you want them answered _fast_ ask them here. 👍 Please ⭐ this repo so others know it was useful to you. thanks! 😄

can you guide me

**Comment by ahmedelq** [comment]
openssl rand 64 | hexdump -v -e '/1 "%02x"'
