### ISSUE TITLE
Link on npmjs site

### ISSUE THREAD

**Issue by andrewgoodchild** [dwyl/hapi-auth-jwt2#49]
Hi

The link on the npmjs site to the git repo is busted:

If you go to: https://www.npmjs.com/package/hapi-auth-jwt2
 
Then go to the link to the git repo on the right hand side it points to: github.com/dwyl/hapi-auth-jwt

It should point to: github.com/dwyl/hapi-auth-jwt2

regards, Andrew

**Comment by nelsonic** [comment]
thanks for pointing this out @andrewgoodchild 
I have updated it.
could you please confirm if its working now?
cheers.

**Comment by andrewgoodchild** [comment]
yep works now :-) 


     On Wednesday, June 17, 2015 8:31 AM, Nelson <notifications@github.com> wrote:
   

 thanks for pointing this out @andrewgoodchild 
I have updated it.
could you please confirm if its working now?
cheers.—

**Comment by nelsonic** [comment]
Fixed. Closing. Thanks.
