### ISSUE TITLE
Cookie dependency has security advisory

### ISSUE THREAD

**Issue by camsteffen** [dwyl/hapi-auth-jwt2#496]
See https://github.com/advisories/GHSA-pxg6-pf52-xh8x

cookie has already been updated in tree so it just needs to be released.

**Comment by nelsonic** [comment]
[`hapi-auth-jwt2@10.7.0`](https://www.npmjs.com/package/hapi-auth-jwt2/v/10.7.0) published to NPM updates all versions of dependencies. 📦 ✅
