### ISSUE TITLE
Nonclear text keys

### ISSUE THREAD

**Issue by andrewgoodchild** [dwyl/hapi-auth-jwt2#50]
Hi

The Readme for jwt2 uses a clear text key.  e.g.

server.auth.strategy('jwt', 'jwt', true,
    { key: 'NeverShareYourSecret', // Never Share your secret key 
      validateFunc: validate       // validate function defined above 
    });

When you use a service like Auth0 to authenticate against, the secret key is not provided in clear text, like the above example.  It looks more like this:

secret = 'Hp-tXXbBwhQeNXXXXXwvPXXXXXTL2ZSZC-XXX-PAKGXXX543XXXXXXcZe'

(n.b.  secrets dont normally contain so many Xs.  I just tweaked mine to 'keep it secret')

Using this type of key with jwt2 (see example below) will not validate the token of the user.

server.auth.strategy('jwt', 'jwt', true,
    { key: 'Hp-tXXbBwhQeNXXXXXwvPXXXXXTL2ZSZC-XXX-PAKGXXX543XXXXXXcZe', 
      validateFunc: validate       // validate function defined above 
    });

After a day of head scratching and digging deeper into JWT2, JWS, Auth0 and jwt.io token validator, it turns out the secret needs to be supplied as a base 64 encoded buffer to JWT2 for JWS to recognise it and validate the user's token.  So to make the key work you need to do the following:

server.auth.strategy('jwt', 'jwt', true,
    { key: Buffer('Hp-tXXbBwhQeNXXXXXwvPXXXXXTL2ZSZC-XXX-PAKGXXX543XXXXXXcZe', 'base64'), 
      validateFunc: validate      
    });

The tip off that you need to do this is on the jwt.io validator, you need to tick off "secret base64 encoded" on the secret . So no one else has to experience the same gnashing of teeth I did, I might suggest adding a section to the readme on dealing with Base64 encoded secret keys.  Something like:

----- Sample text to add to readme ----

Dealing with Base64 encoded secret keys

Some authentication services (like Auth0) provide secret keys encoded in base64,  To find out if your authentication service is one of these services, please try and experiment with the base64 encoded secret options on the validator at http://jwt.io/

If your key is base64 encoded, then for JWT2 to use it you need to convert it to a buffer:

server.auth.strategy('jwt', 'jwt', true,
    { key: Buffer('XXXX-Base64-encoded-secret-XXXXXXXX', 'base64'), 
      validateFunc: validate       
    });

**Comment by nelsonic** [comment]
@andrewgoodchild makes sense.
please submit a Pull Request with this change. 
Thanks! :+1:

**Comment by nelsonic** [comment]
we agree that plain-text keys are undesirable, and in some instances won't work.
We have added a section to the readme advising people to use random alpha-numeric strings for keys. 
@andrewgoodchild if you still want to submit a PR please re-open this issue and submit a PR referencing it.
