### ISSUE TITLE
Specifying allowed algorithms

### ISSUE THREAD

**Issue by walling** [dwyl/hapi-auth-jwt2#51]
Regarding [this vulnerability in JWT](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/), how can I specify the allowed algorithms in `hapi-auth-jwt2`? It could be nice with something like this:

```js
server.auth.strategy('jwt', 'jwt', true, {
  key: 'secret',
  algorithms: [ 'HS256' ],
  validateFunc: validate
});
```

**Comment by walling** [comment]
Ok, I figured this out. I would recommend to document it in the readme though. Otherwise just close this issue.

```js
server.auth.strategy('jwt', 'jwt', true, {
  key: 'secret',
  verifyOptions: {
    algorithms: [ "HS256" ]
  },
  validateFunc: validate
});
```

**Comment by nelsonic** [comment]
@walling thanks for posting this issue. please submit a Pull Request adding this to the README.md so others are aware of it! thanks! :+1:

**Comment by walling** [comment]
I've added a PR. If you have any comments, please do not hesitate to tell me.
