### ISSUE TITLE
Next Release (Major or Minor) ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#54]
Hi @dwyl/doers & friends using _**hapi-auth-jwt2**_ to secure your Hapi.js Apps,
@eventhough has done a _great_ job adding dynamic key support to the plugin!
see: https://github.com/dwyl/hapi-auth-jwt2/pull/53

Which means we need to release the **new feature** in the **npm package** today.

## Question:
should we make this a _**major**_ release e.g. **5.0** to signal to people that there is new functionality ?
_**or**_ (_given that its 100% backwards compatible with previous versions_) 
should we version bump to **4.5.0** so [_**David-DM**_](https://david-dm.org/) does not _force_ people to update?

http://semver.org/ suggests this is a _**minor**_ release because of backward compatibility; so **4.5.0**

what do people think?

**Comment by nelsonic** [comment]
Went with 4.5.0
![hapi-auth-jwt2-new-version-published](https://cloud.githubusercontent.com/assets/194400/8425691/6402e800-1f00-11e5-8e72-12584f42a058.png)
@iteles  thanks for your (_verbal_) feedback.

**Comment by iteles** [comment]
😉 Definitely agree with following semver 👍🏻
