### ISSUE TITLE
jason web token storage

### ISSUE THREAD

**Issue by benjaminlees** [dwyl/hapi-auth-jwt2#55]
from looking at this module it looks like you store the jwt in web storage rather than in a cookie.but doesn't this open you up to xss attacks?

**Comment by nelsonic** [comment]
How so @benjaminlees ?
(Genuinely, please help us understand how ...)

**Comment by benjaminlees** [comment]
As web storage is accessible by javascript on the same domain making it vulnerable to cross site scripting.

**Comment by nelsonic** [comment]
Any more so than cookies...?

**Comment by eventhough** [comment]
@benjaminlees Check out this blog post from Auth0 regarding XSS vs CSRF:

[https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/#xss-xsrf](https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/#xss-xsrf)

**Comment by benjaminlees** [comment]
@eventhough thank you very much. But this article also states that through using the  the HttpOnly cookie flag the cookies are not accessible through javascript and are there  for immune to xxs unlike web  storage.

**Comment by benjaminlees** [comment]
@eventhough I guess that the article also states that  xsrf is a harder attack to protect against then xxs, which is a very good point and one that i had not truly understood.

**Comment by eventhough** [comment]
There are tradeoffs to everything in life. We make decisions based on what
we know at that moment and figure out how to make those choices work down
the line.

**Comment by nelsonic** [comment]
@benjaminlees not all browsers support **HttpOnly cookie**
see: http://resources.infosecinstitute.com/cookies-httponly-flag-problem-browsers/

But we are considering add support for it: https://github.com/dwyl/hapi-auth-jwt2/issues/56

Want to Pair on a Pull Request tomorrow? :wink:

**Comment by benjaminlees** [comment]
@nelsonic definitely that would be awsome!

**Comment by nelsonic** [comment]
@benjaminlees is the code where you used cookies in hapi somewhere on GitHub?

**Comment by eventhough** [comment]
@nelsonic Just updated to version 4.7.0 and I get a weird error in IE9: `Invalid cookie value`

Does IE9 do something differently when it sends cookies over? Is there a flag or something I can set to turn off cookie auth?

**Comment by nelsonic** [comment]
@eventhough oh! where are you seeing that error? (in the browser or in a response from the server?)
Can you upload a ***screenshot*** of the error? (_preferably as a new issue_)

Does your app already use cookies for something other than authentication? (or are you using the **hapi-auth-cookie** plugin in your app?)

If its a show-stopper issue, simply downgrade to the previous version of the **hapi-auth-jwt2** package by specifying v.4.6.0 in your package.json till we are able to identify precisely what the issue is.

Thanks very much for reporting this.

**Comment by eventhough** [comment]
@nelsonic sorry spoke way too soon. I think it has something to do with hapi, not with hapi-auth-jwt2. Have you ever seen this problem before?

https://github.com/hapijs/hapi/issues/2588

I don't use cookies in my project but for some reason hapi does not like whatever IE9 is sending....

**Comment by eventhough** [comment]
@nelsonic All is well. Not sure what IE9 is doing but if you aren't using cookies, make sure you set the route config for state.parse = false;

https://github.com/hapijs/hapi/issues/2513

**Comment by nelsonic** [comment]
Oh wow! `{` and `"` *really* shouldn't cause issues in cookies. 
The cookie spec states that any any [USASCII] character is valid: http://tools.ietf.org/html/rfc6265#section-2.2 so its definitely an IE9 issue not Hapi.js as concluded by **Eran Hammer** in https://github.com/hapijs/hapi/issues/2588
Thankfully using cookies in **hapi-auth-jwt2** will be in the format:
```js
headers: { 
cookie: 'token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTIzLCJuYW1lIjoiQ2hhcmxpZSIsImlhdCI6MTQzNzUxNTE5OH0.xFWe9ccAHqq1bWQ3FvY_plDcY4ClHhm173fxUVHapAE' 
}
```
So I don't expect to ever see this IE9 issue ...

**Comment by nelsonic** [comment]
@eventhough thanks for the heads up!
Did you see the IE9 issue with the previous version of **hapi-auth-jwt2** ?

**Comment by eventhough** [comment]
@nelsonic I saw the same error in 4.6.x so I knew it wasn't hapi-auth-jwt2. A little more sleuthing revealed that IE9 is the culprit. I'm not really using cookies for my app right now so I turned off parsing.

**Comment by nelsonic** [comment]
@eventhough thanks for confirming that.
@benjaminlees can we safely close this issue now? :+1:

**Comment by nelsonic** [comment]
Closing. this was resolved a 3 releases ago. :+1:
