### ISSUE TITLE
 add OPTIONAL HttpOnly cookie support?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#56]
See discussion in: #55 
read: 
+ https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/#xss-xsrf
+ https://www.owasp.org/index.php/HttpOnly

**Comment by nelsonic** [comment]
@eventhough thoughts on adding (_optional_) cookie support?
if a cookie is set and its a valid JTW we attempt to authenticate the request ...

**Comment by eventhough** [comment]
@nelsonic I'll look into this when I have some time. Is there any way we could integrate the official hapi cookie plugin? [https://github.com/hapijs/hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie)

**Comment by nelsonic** [comment]
@eventhough it would be my _preference_ to use the "official" hapi-auth-cookie module in combination with **hapi-auth-jwt2** but its not clear from the docs http://hapijs.com/tutorials/plugins how this would be done...

**Comment by nelsonic** [comment]
@eventhough please see: https://github.com/dwyl/hapi-auth-jwt2/pull/62
Adds 4 lines to the module (_the rest of the PR is tests and docs_)
Usage of cookies is 100% Optional and maintains 100% backward compatibility with previous versions.

**Comment by nelsonic** [comment]
Its up to the developer to decide if they will use HTTP-Only Cookies.
