### ISSUE TITLE
hapi.io integration

### ISSUE THREAD

**Issue by Alterprop** [dwyl/hapi-auth-jwt2#57]
Hi!

I've tried to obtain socket.io token authentication through <a href="https://github.com/sibartlett/hapi-io" target=_blank>hapi.io</a> with no success.  

I'm thinking of bypassing the socket.io authentication to your plugin:

`if (!auth && request.query.Authorization) {   auth =  request.query.Authorization;}`

`var socket = io( "", {query : "Authorization=" + token});`

I feel that this is a erroneous & risky approach, and a waste of resources (I'm using an entire plugin with auth functionalities to just routing socket.io requests)...

Have you any recommendation about your hapi.io's auth integration with your plugin?

Thank you in advance!

**Comment by nelsonic** [comment]
Hi @Alterprop,
We have not listed support for socket.io / hapi.io in this plugin, but it's always been one of our (*very*) "nice-to-have" features!
So, thanks for reminding us! :+1: 
We would love to partner with you on adding this functionality both to your app and the plugin, so if you can give us more detail of your usage, it would help us move forward.
Is your code on GitHub?
Or can you paste an example somewhere in a temporary Gist?
Thanks! :wink:

**Comment by Alterprop** [comment]
Hi, @nelsonic 
Thank you for your answer...

I think that I was wrong from the beginning... I thought that <a href="https://github.com/sibartlett/hapi-io" target=_blank>hapi.io</a> could place the socket.io handshake query on the request's header... magically or something... So, I'm really lost right now about it's use of auth strategies...

However... simply by telling hapi-auth-jwt2 where to find the token (request's query as I wrote before), seems to work for now...

Thank you, again!

**Comment by sibartlett** [comment]
I've updated the hapi-io plugin to automatically map the "Authorization" attribute (from the handshake's querystring or an event's data object) to the Authorization header.

Related ticket here: sibartlett/hapi-io#7

**Comment by Alterprop** [comment]
It work like a charm now...

**Comment by nelsonic** [comment]
Sweet! :lollipop: 
thanks @sibartlett ! :+1:

**Comment by nelsonic** [comment]
Given that this issue relates to the hapi.io module (and is thus out of our control) we are closing.
@sibartlett thanks for confirming that it works.

If anyone else would like to learn how to use Socket.io with Hapi.js, check out our Chat example app:  https://github.com/dwyl/hapi-socketio-redis-chat-example
