### ISSUE TITLE
Ensure not vulnerable to algorithm selection vulnerabilities

### ISSUE THREAD

**Issue by glenjamin** [dwyl/hapi-auth-jwt2#59]
This blog post details the problems: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

The short version is: the algorithm should be selected by the server, never trust the value in the JWT itself.

My suggestion would be to default the algorithms list to `HS256`, and make it move obvious how to change it if needed.

You might already be not vulnerable to this, but it's worth checking to be sure :)

**Comment by nelsonic** [comment]
@glenjamin thanks for getting in touch.
this was addressed by the pull request: https://github.com/dwyl/hapi-auth-jwt2/commit/63dc8aba391b3cc18fc4fd70e62ffebfc3bc2fb0
in: https://github.com/dwyl/hapi-auth-jwt2/issues/51

> See: https://github.com/dwyl/hapi-auth-jwt2#verifyoptions-let-you-define-how-to-verify-the-tokens-optional

**Comment by walling** [comment]
I was the one submitting the pull request for #51. It is worth noting that [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken), which this module depends on, is not vulnerable by default. [Check out the code](https://github.com/auth0/node-jsonwebtoken/blob/master/index.js#L122-L130). I still like to restrict the algorithms to only the one used for signing tokens.

**Comment by nelsonic** [comment]
@glenjamin + @walling what do you think about having a _**default algo**_?

The only reason we left it open was to be compatible with other systems (e.g. someone has a rails app that has to inter-operate with their node/hapi api, by leaving the algo blank the tokens generated on both platforms will be the same...) however this "interoperability" use case has not materialised, so maybe we _should_ add a default (_the strongest_) algo and _**allow**_ people to _**override**_ if they need/want to.

**CC**: @eventhough @alanshaw @besarthoxhaj @harriha @Burka-HWP @poeticninja @bs1180 @iteles  @dschenkelman @nikhilaravi @NataliaLKB @benjaminlees

**Comment by alanshaw** [comment]
:+1: for default secure algo

**Comment by glenjamin** [comment]
It seems like `jsonwebtoken` has reasonably secure defaults, so perhaps it should just be made more obvious that this is the case in the README?

**Comment by walling** [comment]
I think stuff like that should go in the upstream module `jsonwebtoken` that takes care of security. If you take over the security parameters like the default algorithm, then you also need to upgrade it, if it's not the most secure algorithm at some point, etc. In my opinion it's the responsibility of `jsonwebtoken`.

I'm quite happy with it as it is now. You're able to overwrite the value, it's documented in the readme. Perhaps it's not visible enough; I'm not sure about that.

**Comment by nelsonic** [comment]
So, should we update the **README** examples to include an explicit (_strongest_) algorithm...?

**Comment by walling** [comment]
:+1: for that.

**Comment by iteles** [comment]
:+1: Seems like a plan, including some explanation around the issue/linking to this issue to give to context as to why it's the recommended implementation.

**Comment by nelsonic** [comment]
We have updated the usage examples in the REAMDE and Tests to (_strongly_) encourage people to use the stronger algorithm. @glenjamin is this _enough_? (_can we close off this issue_?)
