### ISSUE TITLE
If any cookie is sent, no longer looks in headers for token

### ISSUE THREAD

**Issue by duro** [dwyl/hapi-auth-jwt2#65]
It seems the logic in this plugin trips up if any cookie is sent with the request, but I am attempting to send the token using an Authorization header.

My page sends up a cookie, but it's a bunch of GA stuff and other garbage. However, I am trying to send the token via the Authorization header.

Is what I am trying to do not possible? If I want to use the Authorization header, do I need to make sure my client does not send a cookie?

These seems like an oversight in the logic.

**Comment by duro** [comment]
For example, here is the value of `request.headers.cookie` in my situation:

```
"gwcm=%7B%22expires%22%3Anull%2C%22mobile_number%22%3Anull%2C%22formatted_number%22%3Anull%2C%22fallback%22%3A%223107651600%22%2C%22clabel%22%3A%22SbNVCILRtFcQwcrE6gM%22%2C%22backoff%22%3A1437241242%7D; _ga=GA1.2.1363734468.1432273334"
```

I'm sure this is a bunch of junk left over from some Google Analytics tracking.

**Comment by nelsonic** [comment]
@duro yes, good point. (_**any cookie** will force the cookie branch in the code_)
thanks for informing us of your use-case. (_which will be a **popular** one_)
lets fix that _**now**_.

**Comment by duro** [comment]
@nelsonic The PR above is a start towards a solution, but I don't think it's the complete solution.

**Comment by nelsonic** [comment]
@duro I will code up a more detailed solution and update the tests this morning.
its 4am London time so I'm not at my "real" machine. please version bump in the `package.json` and commit in your PR so I can merge this fix and you can get on with your work :+1: 
Thanks again for informing us!

**Comment by nelsonic** [comment]
@duro keeping this open so we can write a bit more logic for checking the cookies this morning.
do you mind if we use that cookie example you posted (_above_) in our _**regression test**_ ?

**Comment by duro** [comment]
Go for it
