### ISSUE TITLE
If Auth Header Token is Invalid should we attempt to verify URL or Cookie Token?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-jwt2#68]
At the moment the logic in lib/index.js follows a series of `if/else` trees. 
see: https://github.com/dwyl/hapi-auth-jwt2/blob/8793e6d12915c555cf07b64ae4d153ea65862960/lib/index.js#L30-L45

This means that if an `Authorisation Header` is set and the token is _invalid_, we aren't checking for a valid token anywhere else which means that a valid token in a cookie or url token is ignored.

Should we check for a valid Token in one of the other values before rejecting the request?

**Comment by nelsonic** [comment]
Could we *conceivably* use add a `map` in extract.js to look through all possible options?
*currently* `extract.js` looks like this: https://github.com/dwyl/hapi-auth-jwt2/blob/21bb10f48a9afc3baf4438842a3fa0f15ceca073/lib/extract.js

**Comment by bboysathish** [comment]
@nelsonic IMO, the extract.js is working how it should work. We should not keep on looking for valid token in header, then url, then cookie. If a Token is sent to us, it should be either in url , cookie or header. If they sent a invalid token in header and correct token in url (then it may prone to attacks like hackers can give 3 different possible tokens in 3 different places) & more-over client may not aware which token got validated successfully.

**Comment by nelsonic** [comment]
@bboysathish I agree that adding a reducer to check for a Valid JWT in *several* places ***could*** be an attack vector... but it could also simplify things for *bigger* applications which want to have different types of tokens or several types of auth. I'm leaving it for now because *we* (*the* ***existing users*** *of this module*) have ***not requested*** this feature be added. 
Thank you for giving your feedback. closing the issue for now. we can re-open it if someone requests.
:+1:
