### ISSUE TITLE
Push tags/releases to GitHub so we can compare differences between versions easily

### ISSUE THREAD

**Issue by kenkouot** [dwyl/hapi-auth-jwt2#72]
I noticed that you are only updating your tags in npm. Please use GitHub tags/releases as well to allow developers to easily compare new releases to older ones.

**Comment by nelsonic** [comment]
@kenkouot you're absolutely correct! that's 100% my bad. I need to be *Way* more disciplined about release tags (_as @iteles recently pointed out ..._) now that other people are using this package ...
promise to do it from now on. thanks for reminding us! :+1:

**Comment by alanshaw** [comment]
...I'm sure you're all over it but, use [npm version](https://docs.npmjs.com/cli/version)

**Comment by nelsonic** [comment]
Have done for the latest version.
Is there a way of _retrospectively_ creating tags by commit hash?

**Comment by nelsonic** [comment]
@alanshaw have the last two tags been better (more traceable) ?
(Can we close this issue?) Thanks!

**Comment by alanshaw** [comment]
Yes. Although your commit message varies each time so by looking at the commits it's probably not as easy as it could be if you used "npm version".

**Comment by nelsonic** [comment]
Going to follow this awesome example I found from now on: https://github.com/alanshaw/david/releases :+1: 
thanks!

**Comment by nelsonic** [comment]
We've done the last couple of releases following the David-DM example. will keep this up. closing. thanks!
