### ISSUE TITLE
Use err from validateFunc in response?

### ISSUE THREAD

**Issue by alanshaw** [dwyl/hapi-auth-jwt2#77]
Do you think that if err is a boom then it should be used as the first arg to `reply` here?:
https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L62

By calling the callback to validateFunc with an error the caller is explicitly not saying that the token is valid or invalid, just that an error was encountered during validation.

**Comment by nelsonic** [comment]
Doesn't calling the callback with a Boom error signal to the callee that the token is invalid?
Are you saying that if the callee does not handle the error it could be a security hole because the handler could allow someone through with an invalid token?

**Comment by alanshaw** [comment]
So this is about communicating the correct thing to the client.

If a error occurred in my validate function, not a validation error, but for example a database connection error or something. Say I query the database in my validate function - if the database query causes an error, then I'll call the callback passed to my validate function with the database error as a parameter.

Currently hapi-auth-jwt2 will take that error and respond to the client with a "401 unauthorised" regardless. The client is neither authorised, or unauthorised. The error is not a client error, its a server error, so should have a 500 series HTTP response.

I'm suggesting that instead of [replying 401 here](https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L62) we Boom.wrap the error:

```js
reply(Boom.wrap(err))
```

Which will by default respond with a 500 in the case of a generic error, but also allow the validate function to respond with an appropriate error code should it want to, since [wrapping a boom in a boom returns the original boom](https://github.com/hapijs/boom/blob/master/lib/index.js#L15).

**Comment by nelsonic** [comment]
Seems like a sensible suggestion. 
(I'm a fan of providing the most helpful *possible* message back to client request when an error occurs)

Do you have time to submit as PR?
