### ISSUE TITLE
Redirect to login page

### ISSUE THREAD

**Issue by gilly3** [dwyl/hapi-auth-jwt2#78]
What is the correct way to redirect to a login page when authentication fails?

Currently, in my app, when an unauthenticated user hits a page that requires authentication, they see JSON in the browser:

```js
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Token expired",
  "attributes": {
    "error": "Token expired"
  }
}
```

I could always use "try" mode, and then in the handler check `request.auth.isAuthenticated`, but that doesn't seem right.  That's a lot of redundant code.

I feel like I must be missing something fairly obvious.

**Comment by nelsonic** [comment]
Good Question @gilly3 !
`If` ***authentication fails***, you *do* want to send this info to the client (or consumer of the API) so they receive the `401` status code.

If you redirect e.g: `redirect('/login')` they will receive a `302` status code which might not be very informative from a programatic perspective. 

Do you want to *always* redirect to `/login` on auth failure?

see: http://hapijs.com/api

**Comment by gilly3** [comment]
For my routes that serve REST endpoints, a JSON response is perfect.  But, I also have routes that serve regular pages, and a JSON response does not make any sense for those routes.  A redirect may or may not be the right thing in that case.  Perhaps more appropriate would be to send the login html in the response, with a 401 status.

A hapi app should be able to determine the final response when authentication fails.  Leaving the response to an auth scheme is not right.  I think this is a weakness in Hapi's auth API.  I opened [this issue in their repo](https://github.com/hapijs/hapi/issues/2679).

I created a `"login"` scheme that just redirects to login and used multiple auth strategies like this:

```js
server.auth.default({ strategies: ["jwt", "login"] });
```

But found that doesn't work because:

> If the err returned by the reply() method includes a message, no additional strategies will be attempted.

Since `hapi-auth-jwt2` includes a message, my `"login"` strategy was never invoked.  Now, I think it would be wrong to suggest that your plugin stop including error messages... that is useful and necessary information.  This is what I mean about the weakness in the auth API.  Going by the presence or lack of a message to determine whether to invoke additional strategies is just a weird way of doing things.

Here's what I came up with, which works, but seems weird:

```js
server.auth.scheme("login", function (server, options) {
    return {
        authenticate: function (request, reply) {
            server.auth.test("jwt", request, function (err, credentials) {
                if (err) {
                    reply.redirect("/login");
                }
                else {
                    reply.continue({ credentials: credentials });
                }
            });
        }
    };
});
server.auth.strategy("login", "login", true);
```

In the end, I think `hapi-auth-jwt2` is doing the right thing.  To add in hooks to control the output would be trying to do too much.  Hopefully, Hapi will address this with an improved API that allows the app to optionally override the response when authentication fails.

... Unless I'm still missing something.  I'm finding it hard to believe that I'm the first person to want to display a login page when authentication fails.  While the way I've come up with to do it works, it feels like a real hack.

**Comment by eventhough** [comment]
@gilly3 I think you have a few options here. First of all, have you tried setting your jwt strategy to `try` mode? I believe if `try` mode is turned on, Hapi will automatically move down the array of strategies and test each one in order.

See: http://hapijs.com/tutorials/auth#route-configuration

Another option you could try is using a plugin `onPostAuth` which checks whether or not the request `isAuthenticated` and then redirects to /login if failed.

My guess is, most people using jwt strategies are probably building single page apps which means redirection is handled on the front-end.

**Comment by nelsonic** [comment]
@gilly3 what did you decide to do in the end? we would love to help you if you have not yet found a solution ... but if you did get something working, please let us know so we can either expand our readme or close this issue. (we prefer not to have issues open)

**Comment by jalcine** [comment]
[**@nelsonic**](https://github.com/nelsonic) commented on [Aug 27, 2015, 12:47 AM EDT](https://github.com/dwyl/hapi-auth-jwt2/issues/78#issuecomment-135289591 "2015-08-27T04:47:39Z - Replied by Github Comment Enhancer"):
> [@gilly3](https://github.com/gilly3) what did you decide to do in the end? we would love to help you if you have not yet found a solution ... but if you did get something working, please let us know so we can either expand our readme or close this issue. (we prefer not to have issues open)

I think an example of what @eventhough (if not a link to) mentioned can suffice here:

**Comment by gilly3** [comment]
I'm still using my [weird `login` scheme](#issuecomment-128449760).  It still feels wrong, but I'm ok with it.

It looks like `onPostAuth` is done for all requests before it ever reaches the route handler.  I didn't investigate that approach much for fear of code duplication - essentially defining routes in two places.  I'd rather my route decide what happens when authentication fails, not some upstream function.

**Comment by nelsonic** [comment]
@gilly3 agree 100% that using `hooks` (e.g: `onPostAuth`) is sub-optimal.
If you're interested, I'm trying to build a *simple(er)* solution to this *exact* problem...

**Comment by gilly3** [comment]
Yes, I'd love to see it.
