### ISSUE TITLE
Remove Hoek dependency?

### ISSUE THREAD

**Issue by alanshaw** [dwyl/hapi-auth-jwt2#80]
hapi-auth-jwt2  only uses `Hoek.assert` for which it could use the built in [node assert module](https://nodejs.org/api/assert.html) and save some time when npm installing.

**Comment by nelsonic** [comment]
True, at present we are only using **hoek** for:
```js
  Hoek.assert(options, 'options are required for jwt auth scheme'); // pre-auth checks
  Hoek.assert(options.key, 'options must contain secret key or key lookup function'); // no signing key
  Hoek.assert(typeof options.validateFunc === 'function', 'options.validateFunc must be a valid function');
```
https://github.com/dwyl/hapi-auth-jwt2/blob/99507bb459114499da3f789f712b8daf5bf11b92/lib/index.js#L23

node's `assert` appears *functionally* equivalent 
+ https://nodejs.org/api/assert.html#assert_assert_value_message_assert_ok_value_message
+ https://github.com/hapijs/hoek#assertcondition-message

No objection to removing dependency provided we maintain functionality. :+1:
