### ISSUE TITLE
Use of `Authorization` response header

### ISSUE THREAD

**Issue by devinivy** [dwyl/hapi-auth-jwt2#82]
I notice in your examples you send the token back to the client in an `Authorization` header.  I've never seen an `Authorization` header used in a response– only in a request.  Can you explain this decision?  Does the header exist anywhere else in the wild?  I would expect the token to be in the response body or possibly a cookie.  Thanks!

**Comment by nelsonic** [comment]
@devinivy good question. 
putting the JWT token in the `Authorization` header gives us flexibility to send an *actual* response in a web application. For a REST-only App/API you are free to send the JWT as the response body or a cookie. What matters is how the client stores the JWT and sends it back to the Server, which is done in the `Authorization` header (or Cookie or URL Token if you prefer) :+1: 

As for this existing in the "*wild*", I have *not* seen an example of the *server* sending an `Authorisation` header to the client, but there is nothing in the spec to suggest this is an anti-pattern.
see: http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html

If you want to stick to the guidelines you would do follow this example: http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html#ExAccTokResp

```js
  HTTP/1.1 200 OK
  Content-Type: application/json;charset=UTF-8
  Cache-Control: no-store
  Pragma: no-cache

  {
    "access_token":"mF_9.B5f-4.1JqM",
    "token_type":"Bearer",
    "expires_in":3600,
    "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA"
  }
```

**Comment by nelsonic** [comment]
@devinivy are you satisfied with the answer? if you prefer to use a different header, please let us know. we can always add that in as an option. otherwise, please close the issue so it doesn't stay "*hanging*". thanks! :+1:

**Comment by devinivy** [comment]
Thanks for the clarification!  It seems like it's only in examples/suggestions and not anywhere in the library, so I have no issues with this.  I would probably use a custom `X-*` style header just to indicate that the header is non-standard (I was a little confused seeing a familiar header in an unfamiliar context), but I see what you're doing now and it seems reasonable!

**Comment by leebenson** [comment]
Sorry for reviving a closed issue; just wanted to clarify that use of an `X-*` header is against [RFC 6648](http://tools.ietf.org/html/rfc6648) recommendations as of June 2012. I think it's probably more sensible to stick with an `Authorization` header in the _response_, in the same way it's used as a 'request'.

Of course, one reason to use headers at all and not just stick it in the body is that the body response may be context-sensitive. As an example, I'm currently using `Authorization` alongside GraphQL. Merging the JWT with the JSON body would be messy and would, in fact, interfere with the body.

Just a heads up.

**Comment by ckhawand** [comment]
> 

How about using the WWW-Authenticate header in the response to relay back the token (WWW-Authenticate: Bearer {token})?
