### ISSUE TITLE
hapi.transmit.js throws "Error: 'name' and 'value' are required for setHeader() when my validateFunc returns callback(null, true)

### ISSUE THREAD

**Issue by rainabba** [dwyl/hapi-auth-jwt2#84]
When I `return callback(null, false)`, there is no error.

**The full stack** *(I removed yar since it was at the bottom of the stack and I wanted to reduce variables. The issue remains)*
```
Debug: internal, implementation, error
    Error: "name" and "value" are required for setHeader().
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at Object.internals.transmit (node_modules\hapi\lib\transmit.js:254:25)
    at node_modules\hapi\lib\transmit.js:34:26
    at Function.internals.Auth.response (node_modules\hapi\lib\auth.js:406:16)
    at node_modules\hapi\lib\transmit.js:142:25
    at internals.Response._streamify (node_modules\hapi\lib\response.js:491:12)
    at internals.Response._marshal (node_modules\hapi\lib\response.js:437:21)
    at node_modules\hapi\lib\transmit.js:122:18
    at node_modules\hapi\lib\transmit.js:539:20
    at done (node_modules\hapi\node_modules\items\lib\index.js:63:25)
    at node_modules\hapi\lib\transmit.js:512:20
    at Object.exports.parallel (node_modules\hapi\node_modules\items\lib\index.js:70:13)
    at Object.internals.state (node_modules\hapi\lib\transmit.js:508:11)
    at Object.internals.marshal (node_modules\hapi\lib\transmit.js:96:15)
    at Object.exports.send (node_modules\hapi\lib\transmit.js:27:15)
    at node_modules\hapi\lib\request.js:416:18
    at node_modules\hapi\node_modules\hoek\lib\index.js:841:22
    at process._tickDomainCallback (node.js:381:11)
```

**My code for testing (just getting the plugin working)**
```
jwtValidate = function(decoded, request, callback) {
	// do your checks to see if the person is valid
	vtv.logger.debug( { jwtDecoded: decoded } );
	//return callback(null, false);  // I get a proper 401, Invalid credentials here
	return callback(null, true); // This throws the stack above
}
```

**I'm registering the strategy with**
```
server.auth.strategy('jwt', 'jwt', false, {
	key: 'mysecretkey',
	validateFunc: jwtValidate,
	verifyOptions: {
		algorithms: ['HS256']
	},
});
```

**Comment by nelsonic** [comment]
@rainabba thanks for getting in touch. 
that stack trace certainly looks *interesting*, 
however there's no mention of the **hapi-auth-jwt2** plugin in the stack trace ...

Can you please tell us which version of Hapi.js you are using?
have you upgraded to v.9.0.1?

**Comment by rainabba** [comment]
While searching for the more general error message, I noticed a pattern which led me to the cause which should have been more obvious to me. 1st, ANY call to reply().header() which provides an undefined value will cause this error and apparently will never reference the plugin, even if it's at fault. In my case, it was the handler for this route I used for testing which on a successful auth, would execute `reply({ text: "You used a token" }).header("Authorization", request.headers.authorization);` Since request.headers.authorization was undefined, BOOM! Entirely my fault and now I must go determine if that value should be undefined (first time messing with JWT and Authorization header).

Hope this helps someone else anyway :)

**Comment by rainabba** [comment]
Oh yes, using Hapi 8.x. Should I give 9.x a shot or were you concerned that was related?

**Comment by nelsonic** [comment]
Thanks for updating & closing the issue. 
You should probably update to `9.0.1` at some point because it adds a few fixes.
But you'll be fine on `8.x` for now.
:+1:

**Comment by rainabba** [comment]
Thanks for the quick reply and the plugin.

**Comment by nelsonic** [comment]
@rainabba any time!
Thanks for *using* the plugin! if you find it useful, please :star:
All the best!
