### ISSUE TITLE
Error when using sample

### ISSUE THREAD

**Issue by rosshigh** [dwyl/hapi-auth-jwt2#87]
I'm getting the following error when trying to use the example code.  I haven't made any changes to the code.

C:\code\class\hapi\Test\node_modules\hapi\lib\server.js:242
            return callback();
                   ^
TypeError: undefined is not a function
    at C:\code\class\hapi\Test\node_modules\hapi\lib\server.js:242:20
    at C:\code\class\hapi\Test\node_modules\hapi\node_modules\hoek\lib\index.js:841:22
    at process._tickDomainCallback (node.js:381:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

I'm using the following versions:

    "hapi": "^9.0.2",
    "hapi-auth-jwt2": "^5.0.2"

**Comment by nelsonic** [comment]
@rosshigh thanks for alerting us to this! we are investigating now.
From the stack trace you are using Windows. Can you let us know what version of Node or io.js you are running?

**Comment by rosshigh** [comment]
node version 0.12.7

**Comment by diffsky** [comment]
In hapi 9 you have to provide a callback to `server.start`. The error message could be more helpful in this regard. See https://github.com/hapijs/hapi/issues/2682

You can fix the example code with:
```
server.start(function () {
    console.log('Server running at:', server.info.uri);
});
```

**Comment by nelsonic** [comment]
@diffsky yes! do you have time to submit a PR to the Readme/Example code correcting the example?

**Comment by diffsky** [comment]
Sure!

**Comment by nelsonic** [comment]
Sweet! :lollipop: 
Thanks!

**Comment by nelsonic** [comment]
@rosshigh please ***re***-copy-paste the examples and re-try. thanks!

**Comment by rosshigh** [comment]
Thanks!

**Comment by nelsonic** [comment]
The *internet* ( @diffsky ) to the rescue! 
Thanks for using the plugin! let us know if you have any other questions! :+1:
