### ISSUE TITLE
How to configure Custom Header and Payload 

### ISSUE THREAD

**Issue by Faizranas** [dwyl/hapi-auth-jwt2#90]
Hi, How to provide custom header and payload options in JWT2 plug-in. I saw your example but couldn't figure it out.  I see following predefined Header & Payload when I decode the data.
{
  "typ": "JWT",
  "alg": "HS256"
}

{
  "id": 1,
  "name": "Anthony Valid User",
  "iat": 1425473535,
} 

Please let me know how to change these options.

Regards,
Faiz

**Comment by nelsonic** [comment]
@Faizranas thanks for getting in touch!
you add the payload entries to the object which you then encode using `JWT.sign`
have you had a look at the guide: https://github.com/dwyl/learn-json-web-tokens

**Comment by Faizranas** [comment]
Thank you for your quick response. Yes, I checked that but please let me know how to pass custom payload data in Server strategy method. Actually I have to pass that custom data to JWT2 when user Logins to generate Unique Key each time for each user. I tried to hard code payload data in strategy method but it is not taking.

 server.auth.strategy('token', 'jwt', true,
    { 
      payload:{name:"abc"},
      key: privateKey,          // Never Share your secret key 
      validateFunc: validate,
       // validate function defined above 
      verifyOptions: { 
      algorithms: [ 'HS256' ], 
      ignoreExpiration: false,
      exp:Math.floor(new Date().getTime()/1000)+60*2
      } // pick a strong algorithm 
    });

**Comment by iteles** [comment]
@Faizranas you don't have to pass the custom payload data into the server strategy.
Also you don't have to pass the custom data into JWT *each time*.

How are you payload which you will `JWT.sign` ?
is your code on github so we can walk you through setting this up ...

Have you had a look at our "**production-ready***" **example**: https://github.com/dwyl/hapi-auth-jwt2-example ?

You define the ***payload options*** with what ever you want them to be (***once***) 
e.g: https://github.com/dwyl/hapi-auth-jwt2-example/blob/343520418f7a9de920861d14d766f46c450c42ea/index.js#L82-L86

***Sign*** the JSON object using `JWT.sign` 
e.g: https://github.com/dwyl/hapi-auth-jwt2-example/blob/343520418f7a9de920861d14d766f46c450c42ea/index.js#L90

and then send that token to the client:
e.g: https://github.com/dwyl/hapi-auth-jwt2-example/blob/343520418f7a9de920861d14d766f46c450c42ea/index.js#L94

**Comment by nelsonic** [comment]
@Faizranas please let us know if you are still stuck with this. (_we're here to help_)

**Comment by Faizranas** [comment]
Thank you very much for your guidance. I understood the points. Can you please clarify one more point below.
What is the use of "expiresInMinutes or expiresInSeconds"  property? Will JWT2 reject the token internally if it receives the request after specified time? Do I have to pass this property in JWT.sign Method or somewhere else. I specified var token = jwt.sign(session, privateKey,{expiresInMinutes:2}); but JWT2 doesn't reject the request after that time stamp. Please let me know  if I have to do custom validation.

**Comment by Faizranas** [comment]
Once again thanks a lot. It is working for me.

**Comment by nelsonic** [comment]
@Faizranas thanks for asking clarifying questions; you are helping us to improve the documentation in the module so it becomes more useful for others!
Please :star: the repo to signal to others that you find it *useful*.
Thanks again! :tada:
