### ISSUE TITLE
Token in POST Payload

### ISSUE THREAD

**Issue by MWGitHub** [dwyl/hapi-auth-jwt2#93]
Is it possible to have the token in a POST's payload for authentication? I'm trying to avoid preflight so right now I'm putting the token in the query. It works fine though I would like to keep everything in the payload.

**Comment by nelsonic** [comment]
@MWGitHub at present we only have Tokens in Headers, Query or Cookie.
Are you proposing we check for a JWT in the Body (payload) of the POST request too?
We have never had this as a use-case, but it is feasible to implement...

**Comment by MWGitHub** [comment]
Yup, I've tried adding payload checking to the extract function but I could not get the payload.

What I'm trying to do: 
From a site with a different IP/port than the API server, send a POST request to the API server that requires authentication without preflight happening.

When I add headers to a POST request from one server to another in Chrome the request gets preflighted, including when I add an authorization header to the request.
I'm using a content type of application/x-www-form-urlencoded for the requests.
Preflight does not seem to happen as long as I do not have any headers set.

**Comment by nelsonic** [comment]
@MWGitHub *very* interesting! can you paste a stack trace, error message or screenshot of the error you are seeing? we'd love to help dissect and resolve the issue.

**Comment by MWGitHub** [comment]
I don't think there's an error, it's just that when I send a request with a header it sends a preflight so my hapi server would get a request for:
`150824/150739.913, [response], http://0.0.0.0:8080: options /api/task/create {} 404 (2ms) `
which I do not want the API server to respond to, so I do not have a route for the options method.
The route is set up with:
```javascript
{
    method: 'POST',
    path: 'api/task/create',
    handler: TaskHandler.create,
    config: {
        auth: 'jwt',
        validate: {
            payload: {
                list_id: Joi.number().integer().required(),
                title: Joi.string().min(1).max(30).required(),
            }
        },
        cors: true
    }
},
```

I'm using reqwest to send requests to the API server from another server with a different port at http://0.0.0.0:8000

In this case the request would look something like:
```javascript
request({  
    url: mwtest.xyz:8080/api/task/create, // Host file redirecting 0.0.0.0 to mwtest.xyz
    method: 'POST',
    contentType: 'application/x-www-form-urlencoded',
    crossOrigin: true,
    // It doesn't matter what I put in the header, having a header will make an options preflight request
    headers: {
        authentication: 'Bearer ' + AuthStore.getJWT() // Retrieves the JWT token
    },
    data: {list_id: 1, title: 'test'},
    success: function(resp) { console.log(resp) },
    error: function(err) { console.log(err) }
})
```
Which first sends a preflight request to `150824/150739.913, [response], http://0.0.0.0:8080: options /api/task/create {} 404 (2ms)` that my API server does not respond to resulting in this error I get in chrome:
`
XMLHttpRequest cannot load http://mwtest.xyz:8080/api/task/create. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mwtest.xyz:8000' is therefore not allowed access. The response had HTTP status code 404.
`

When making the request with:
```javascript
request({  
    url: 'mwtest.xyz:8080/api/task/create?token=' + AuthStore.getJWT(),
    method: 'POST',
    contentType: 'application/x-www-form-urlencoded',
    crossOrigin: true,
    data: {list_id: 1, title: 'test'},
    success: function(resp) { console.log(resp) },
    error: function(err) { console.log(err) }
})
```
Results in no preflight request so the API server gets the following request: 
`150824/150616.243, [response], http://0.0.0.0:8080: post /api/task/create {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MjcwLCJpYXQiOjE0NDAxOTQyNTh9.QVtFXwhPK_snxT7kY2MxvwsxYY_cd13ueMEXHec4AyU"} 200 (33ms)`
Everything works fine in this request, though requires the token to be in the query when not using cookies.

Now that I think about it more, if authorization from the POST body were added, I'm not sure I would use it over a query. It would be less convenient to use as every route that validated the payload would require a token field vs just having a function that appends the token to a request.

**Comment by nelsonic** [comment]
Yeah, looks like the query parameter is actually easier to reason with in your case and will result in the same amount of code being written as compared to using post body.

**Comment by MWGitHub** [comment]
Looks to be that way, going to use query for passing the token, thanks!
